#ifndef PIKACHU_SKEL_H
#define PIKACHU_SKEL_H

#include "z64.h"

extern u64 Armature_yellow_ci4[];
extern u64 Armature_yellow_pal_rgba16[];
extern u64 Armature_back_ci4[];
extern u64 Armature_back_pal_rgba16[];
extern u64 Armature_tail_ci4[];
extern u64 Armature_tail_pal_rgba16[];
extern u64 Armature_eyes_happy_ci4[];
extern u64 Armature_eyes_happy_pal_rgba16[];
extern u64 Armature_mouth_happy_ci4[];
extern u64 Armature_mouth_happy_pal_rgba16[];
extern Vtx Armature_body_mesh_layer_Opaque_vtx_0[21];
extern Gfx Armature_body_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_body_mesh_layer_Opaque_vtx_1[36];
extern Gfx Armature_body_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_tail_1_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_tail_1_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_tail_2_mesh_layer_Opaque_vtx_0[6];
extern Gfx Armature_tail_2_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_tail_3_mesh_layer_Opaque_vtx_0[5];
extern Gfx Armature_tail_3_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_thigh_l_mesh_layer_Opaque_vtx_0[12];
extern Gfx Armature_thigh_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_knee_l_mesh_layer_Opaque_vtx_0[14];
extern Gfx Armature_knee_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_feet_l_mesh_layer_Opaque_vtx_0[6];
extern Gfx Armature_feet_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_thigh_r_mesh_layer_Opaque_vtx_0[12];
extern Gfx Armature_thigh_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_knee_r_mesh_layer_Opaque_vtx_0[16];
extern Gfx Armature_knee_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_feet_r_mesh_layer_Opaque_vtx_0[6];
extern Gfx Armature_feet_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_head_mesh_layer_Opaque_vtx_0[11];
extern Gfx Armature_head_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_head_mesh_layer_Opaque_vtx_1[32];
extern Gfx Armature_head_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_head_mesh_layer_Opaque_vtx_2[7];
extern Gfx Armature_head_mesh_layer_Opaque_tri_2[];
extern Vtx Armature_hear_l_mesh_layer_Opaque_vtx_0[10];
extern Gfx Armature_hear_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_hear_l_mesh_layer_Opaque_vtx_1[10];
extern Gfx Armature_hear_l_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_hear_r_mesh_layer_Opaque_vtx_0[10];
extern Gfx Armature_hear_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_hear_r_mesh_layer_Opaque_vtx_1[10];
extern Gfx Armature_hear_r_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_mouth_mesh_layer_Opaque_vtx_0[22];
extern Gfx Armature_mouth_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_mouth_mesh_layer_Opaque_vtx_1[13];
extern Gfx Armature_mouth_mesh_layer_Opaque_tri_1[];
extern Vtx Armature_arm_l_mesh_layer_Opaque_vtx_0[7];
extern Gfx Armature_arm_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_hand_l_mesh_layer_Opaque_vtx_0[11];
extern Gfx Armature_hand_l_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_arm_r_mesh_layer_Opaque_vtx_0[9];
extern Gfx Armature_arm_r_mesh_layer_Opaque_tri_0[];
extern Vtx Armature_hand_r_mesh_layer_Opaque_vtx_0[8];
extern Gfx Armature_hand_r_mesh_layer_Opaque_tri_0[];
extern Gfx mat_Armature_f3dlite_material_004_layerOpaque[];
extern Gfx mat_Armature_body_layerOpaque[];
extern Gfx mat_Armature_tail_layerOpaque[];
extern Gfx mat_Armature_eyes_layerOpaque[];
extern Gfx mat_Armature_black_layerOpaque[];
extern Gfx mat_Armature_mouth_layerOpaque[];
extern Gfx Armature_body_mesh_layer_Opaque[];
extern Gfx Armature_tail_1_mesh_layer_Opaque[];
extern Gfx Armature_tail_2_mesh_layer_Opaque[];
extern Gfx Armature_tail_3_mesh_layer_Opaque[];
extern Gfx Armature_thigh_l_mesh_layer_Opaque[];
extern Gfx Armature_knee_l_mesh_layer_Opaque[];
extern Gfx Armature_feet_l_mesh_layer_Opaque[];
extern Gfx Armature_thigh_r_mesh_layer_Opaque[];
extern Gfx Armature_knee_r_mesh_layer_Opaque[];
extern Gfx Armature_feet_r_mesh_layer_Opaque[];
extern Gfx Armature_head_mesh_layer_Opaque[];
extern Gfx Armature_hear_l_mesh_layer_Opaque[];
extern Gfx Armature_hear_r_mesh_layer_Opaque[];
extern Gfx Armature_mouth_mesh_layer_Opaque[];
extern Gfx Armature_arm_l_mesh_layer_Opaque[];
extern Gfx Armature_hand_l_mesh_layer_Opaque[];
extern Gfx Armature_arm_r_mesh_layer_Opaque[];
extern Gfx Armature_hand_r_mesh_layer_Opaque[];
extern FlexSkeletonHeader Armature;
#define ARMATURE_ROOT_POS_LIMB 0
#define ARMATURE_ROOT_ROT_LIMB 1
#define ARMATURE_BODY_LIMB 2
#define ARMATURE_TAIL_1_LIMB 3
#define ARMATURE_TAIL_2_LIMB 4
#define ARMATURE_TAIL_3_LIMB 5
#define ARMATURE_THIGH_L_LIMB 6
#define ARMATURE_KNEE_L_LIMB 7
#define ARMATURE_FEET_L_LIMB 8
#define ARMATURE_THIGH_R_LIMB 9
#define ARMATURE_KNEE_R_LIMB 10
#define ARMATURE_FEET_R_LIMB 11
#define ARMATURE_HEAD_LIMB 12
#define ARMATURE_HAT_LIMB 13
#define ARMATURE_HEAR_L_LIMB 14
#define ARMATURE_HEAR_R_LIMB 15
#define ARMATURE_MOUTH_LIMB 16
#define ARMATURE_SHOULDER_L_LIMB 17
#define ARMATURE_ARM_L_LIMB 18
#define ARMATURE_HAND_L_LIMB 19
#define ARMATURE_SHOULDER_R_LIMB 20
#define ARMATURE_ARM_R_LIMB 21
#define ARMATURE_HAND_R_LIMB 22
#define ARMATURE_NUM_LIMBS 23

#endif
