#ifndef PIKACHU_SSBB_SPECIALAIRLWDISCHARGEEND_H
#define PIKACHU_SSBB_SPECIALAIRLWDISCHARGEEND_H

#include "z64.h"

extern AnimationHeader pikachu_ssbb_SpecialAirLwDischargeEnd_anim;

#endif // PIKACHU_SSBB_SPECIALAIRLWDISCHARGEEND_H
