/**
 * mm_asset_loader.cpp - MM Asset Detection and Loading
 *
 * Detects and loads assets from mm.o2r (generated by 2Ship2Harkinian Keiichi Alfa 4.0.0+)
 * This allows Transformation Masks to use actual MM models, audio, and animations.
 *
 * DEPENDENCY: 2Ship2Harkinian Keiichi Alfa 4.0.0 or later
 * https://github.com/HarbourMasters/2ship2harkinian/releases/tag/4.0.0
 *
 * Users must:
 * 1. Own a legal copy of Majora's Mask (US 1.0 or US GC)
 * 2. Run 2Ship2Harkinian to extract mm.o2r from their ROM
 * 3. Place mm.o2r in the same folder as soh.exe (alongside oot.o2r)
 *
 * NO RECOMPILATION NEEDED - just drop mm.o2r and enable the feature.
 */

#include "mm_asset_loader.h"
#include <filesystem>
#include <cstring>
#include <libultraship/libultraship.h>
#include <libultraship/log/luslog.h>
#include "soh/OTRGlobals.h"
#include "soh/ResourceManagerHelpers.h"
#include "functions.h" // For Audio_SetFontInstrument, AudioLoad_IsFontLoadComplete

// Logging macros (same pattern as mm_anim_loader.c)
#define MMASSETS_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)
#define MMSFX_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)

// Static state - base MM archive
static bool sMmO2rDetected = false;
static bool sMmO2rLoaded = false;
static bool sInitialized = false;
static std::string sMmO2rPath;
static std::shared_ptr<Ship::Archive> sMmArchive; // Reference to mm.o2r archive for archive-specific loading

// Mod override archive (higher priority than mm.o2r)
static bool sModO2rDetected = false;
static bool sModO2rLoaded = false;
static std::string sModO2rPath;
static std::shared_ptr<Ship::Archive> sModArchive; // Reference to mod archive

// Mod archive names to search for (in priority order)
static const char* sModArchiveNames[] = {
    "mm-mod.o2r",      // Primary mod file
    "mm-custom.o2r",   // Alternative name
    "mm-override.o2r", // Alternative name
};
static const int sModArchiveCount = sizeof(sModArchiveNames) / sizeof(sModArchiveNames[0]);

// appShortName is defined in OTRGlobals.h as const std::string

/**
 * Check if mm.o2r exists in any of the app directories
 * Uses the same search paths as oot.o2r
 */
static bool DetectMmO2r() {
    // Search for mm.o2r using the same method as oot.o2r
    std::string mmPath = Ship::Context::LocateFileAcrossAppDirs("mm.o2r", appShortName);
    if (!mmPath.empty() && std::filesystem::exists(mmPath)) {
        sMmO2rPath = mmPath;
        MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", mmPath.c_str());
        return true;
    }

    // Also check current working directory
    if (std::filesystem::exists("mm.o2r")) {
        sMmO2rPath = "mm.o2r";
        MMASSETS_LOG("[MM Assets] Found mm.o2r in current directory");
        return true;
    }

    // Check build output directories (for development)
    const char* buildPaths[] = {
        "x64/Debug/mm.o2r",
        "x64/Release/mm.o2r",
        "build/x64/mm.o2r",
        "../mm.o2r",
    };
    for (const char* path : buildPaths) {
        if (std::filesystem::exists(path)) {
            sMmO2rPath = path;
            MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", path);
            return true;
        }
    }

    MMASSETS_LOG("[MM Assets] mm.o2r NOT FOUND");
    return false;
}

/**
 * Check if a mod .o2r exists that can override mm.o2r assets
 * Searches for mm-mod.o2r, mm-custom.o2r, etc.
 */
static bool DetectModO2r() {
    for (int i = 0; i < sModArchiveCount; i++) {
        const char* modName = sModArchiveNames[i];

        // Search using standard path resolver
        std::string modPath = Ship::Context::LocateFileAcrossAppDirs(modName, appShortName);
        if (!modPath.empty() && std::filesystem::exists(modPath)) {
            sModO2rPath = modPath;
            MMASSETS_LOG("[MM Assets] Found mod override: %s", modPath.c_str());
            return true;
        }

        // Check current directory
        if (std::filesystem::exists(modName)) {
            sModO2rPath = modName;
            MMASSETS_LOG("[MM Assets] Found mod override in current directory: %s", modName);
            return true;
        }
    }

    return false;
}

/**
 * Load mod .o2r into the archive manager (before mm.o2r for priority)
 */
static bool LoadModO2r() {
    if (sModO2rLoaded || sModO2rPath.empty()) {
        return sModO2rLoaded;
    }

    if (!std::filesystem::exists(sModO2rPath)) {
        return false;
    }

    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sModO2rPath);
        if (archive != nullptr) {
            sModArchive = archive;
            sModO2rLoaded = true;
            MMASSETS_LOG("[MM Assets] Loaded mod override archive: %s", sModO2rPath.c_str());
            return true;
        }
    }

    return false;
}

/**
 * Load mm.o2r into the archive manager
 * Same pattern as oot-mq.o2r loading in OTRGlobals::Initialize()
 */
static bool LoadMmO2r() {
    if (sMmO2rLoaded) {
        return true;
    }

    if (sMmO2rPath.empty() || !std::filesystem::exists(sMmO2rPath)) {
        MMASSETS_LOG("[MM Assets] Cannot load - path empty or file doesn't exist");
        return false;
    }

    // Add mm.o2r to the archive manager, then REORDER so it has LOWEST priority.
    // CRITICAL: mm.o2r contains resources with the SAME paths as oot.otr
    // (e.g., objects/object_okuta/gOctorokSkel) but with different data
    // (MM Octorok has 16 limbs, OOT has 38). Ship uses "last-added-wins" priority,
    // so without reordering, mm.o2r shadows OOT → assertion crash.
    //
    // By moving mm.o2r to the FRONT of the archive list (lowest priority):
    // - MM-unique paths (icon_item_static_yar, object_link_goron, etc.) are found
    //   → icon replacements (Deku replaces Skull) work
    // - Shared paths (objects/object_okuta) resolve to OOT version (higher priority)
    //   → no assertion crashes
    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sMmO2rPath);
        if (archive != nullptr) {
            sMmO2rLoaded = true;
            sMmArchive = archive;

            // Reorder: move mm.o2r to FRONT (lowest priority), keep OOT archives after
            auto currentArchives = archiveManager->GetArchives();
            if (currentArchives && currentArchives->size() > 1) {
                auto reordered = std::make_shared<std::vector<std::shared_ptr<Ship::Archive>>>();
                // mm.o2r first (lowest priority)
                reordered->push_back(archive);
                // All other archives after (higher priority = OOT wins for shared paths)
                for (auto& existing : *currentArchives) {
                    if (existing != archive) {
                        reordered->push_back(existing);
                    }
                }
                archiveManager->SetArchives(reordered);
                MMASSETS_LOG("[MM Assets] Loaded mm.o2r at lowest priority (pos 0 of %zu archives)", reordered->size());
            } else {
                MMASSETS_LOG("[MM Assets] Loaded mm.o2r (single archive, ptr=%p)", (void*)archive.get());
            }
            return true;
        } else {
            MMASSETS_LOG("[MM Assets] Failed to add mm.o2r as archive");
            return false;
        }
    }

    MMASSETS_LOG("[MM Assets] No archive manager available");
    return false;
}

// =============================================================================
// C API Implementation
// =============================================================================

extern "C" {

void MmAssets_Init(void) {
    if (sInitialized) {
        return;
    }

    // Detect base MM archive
    sMmO2rDetected = DetectMmO2r();

    // Detect mod override archive
    sModO2rDetected = DetectModO2r();

    sInitialized = true;

    // Load base MM archive FIRST (lower priority)
    if (sMmO2rDetected) {
        LoadMmO2r();
    }

    // Load mod archive LAST (higher priority - overrides mm.o2r)
    // Ship's ResourceManager uses last-added-wins for duplicate resources
    if (sModO2rDetected) {
        LoadModO2r();
    }

    // Summary
    if (sModO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Mod override active - %s overrides mm.o2r", sModO2rPath.c_str());
    }
}

u8 MmAssets_IsAvailable(void) {
    if (!sInitialized) {
        MmAssets_Init();
    }
    return sMmO2rDetected ? 1 : 0;
}

u8 MmAssets_IsLoaded(void) {
    return sMmO2rLoaded ? 1 : 0;
}

u8 MmAssets_IsModLoaded(void) {
    return sModO2rLoaded ? 1 : 0;
}

const char* MmAssets_GetModPath(void) {
    return sModO2rPath.c_str();
}

const char* MmAssets_GetRequiredVersion(void) {
    return "2Ship2Harkinian Keiichi Alfa 4.0.0";
}

const char* MmAssets_GetDownloadUrl(void) {
    return "https://github.com/HarbourMasters/2ship2harkinian/releases/tag/4.0.0";
}

const char* MmAssets_GetPath(void) {
    return sMmO2rPath.c_str();
}

/**
 * Check if any user mod archive (not mm.o2r, not mm-mod.o2r) overrides a MM resource.
 * This allows .otr files in the mods/ folder to override mm.o2r assets.
 *
 * Priority order (highest first):
 *   1. User mods in mods/ folder (if they contain MM paths)
 *   2. mm-mod.o2r / mm-custom.o2r / mm-override.o2r
 *   3. mm.o2r (base MM archive)
 *
 * OOT mods don't interfere because OOT and MM use different path namespaces
 * (e.g., "textures/icon_item_static/..." vs "icon_item_static_yar/...").
 *
 * @param path Resource path (with or without __OTR__ prefix)
 * @return Archive containing the override, or nullptr if no mod override exists
 */
static std::shared_ptr<Ship::Archive> MmAssets_FindModOverride(const char* path) {
    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager)
        return nullptr;

    auto archiveManager = resourceManager->GetArchiveManager();
    if (!archiveManager)
        return nullptr;

    auto archives = archiveManager->GetArchives();
    if (!archives)
        return nullptr;

    // Strip __OTR__ prefix - archives index files without it
    std::string cleanPath = path;
    if (cleanPath.length() > 7 && cleanPath.substr(0, 7) == "__OTR__") {
        cleanPath = cleanPath.substr(7);
    }

    // Iterate in reverse (last-added archives have highest priority in Ship)
    for (auto it = archives->rbegin(); it != archives->rend(); ++it) {
        auto& archive = *it;

        // Skip mm.o2r - we want mods to override it
        if (archive == sMmArchive)
            continue;

        // Skip mm-mod.o2r if loaded (it's handled by the standard loading path)
        if (sModO2rLoaded && !sModO2rPath.empty() && archive->GetPath() == sModO2rPath)
            continue;

        if (archive->HasFile(cleanPath)) {
            MMASSETS_LOG("[MM Assets] Mod override found: %s in %s", path, archive->GetPath().c_str());
            return archive;
        }
    }

    return nullptr;
}

/**
 * Load a resource from mm.o2r, with support for mod overrides from the mods/ folder.
 * Path format follows 2Ship convention: "objects/object_link_goron/gLinkGoronSkel"
 *
 * Loading priority:
 *   1. User .otr in mods/ folder (if it contains this MM path)
 *   2. mm-mod.o2r (via standard archive priority)
 *   3. mm.o2r (base)
 *
 * @param path Resource path within mm.o2r
 * @return Pointer to loaded resource, or NULL if not found/not loaded
 */
void* MmAssets_LoadResource(const char* path) {
    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] No resource manager");
        return nullptr;
    }

    // Check if a mod archive in the mods/ folder overrides this MM resource.
    // mm.o2r is loaded after the mods/ folder so it wins in mFileToArchive (last-added-wins).
    // We explicitly check mod archives here to restore user mod priority over mm.o2r.
    auto modArchive = MmAssets_FindModOverride(path);
    if (modArchive) {
        Ship::ResourceIdentifier identifier(path, 0, modArchive);
        auto resource = resourceManager->LoadResource(identifier);
        if (resource) {
            void* ptr = resource->GetRawPointer();
            MMASSETS_LOG("[MM Assets] Loaded from mod: %s -> %p", path, ptr);
            return ptr;
        }
    }

    // No mod override - load explicitly from mm.o2r via ResourceIdentifier.
    // We do NOT use the general resourceManager->LoadResource(path) because
    // that would search ALL archives (including oot.otr) and might return
    // OOT data for paths that exist in both games.
    if (sMmArchive) {
        Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
        auto resource = resourceManager->LoadResource(identifier);
        if (resource) {
            void* ptr = resource->GetRawPointer();
            MMASSETS_LOG("[MM Assets] Loaded from mm.o2r: %s -> %p", path, ptr);
            return ptr;
        }
    }

    MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    return nullptr;
}

/**
 * Load a resource from mm.o2r and get its size, with mod override support.
 * @param path Resource path
 * @param outSize Output: size in bytes
 * @return Pointer to loaded resource, or NULL if not found
 */
void* MmAssets_LoadResourceWithSize(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] No resource manager");
        return nullptr;
    }

    // Check mod override (if a mod archive is loaded)
    if (sModArchive) {
        Ship::ResourceIdentifier modId(path, 0, sModArchive);
        auto resource = resourceManager->LoadResource(modId);
        if (resource) {
            void* ptr = resource->GetRawPointer();
            size_t size = resource->GetPointerSize();
            if (outSize)
                *outSize = size;
            MMASSETS_LOG("[MM Assets] Loaded from mod with size: %s -> %p (%zu bytes)", path, ptr, size);
            return ptr;
        }
    }

    // No mod override - load explicitly from mm.o2r
    if (sMmArchive) {
        Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
        auto resource = resourceManager->LoadResource(identifier);
        if (resource) {
            void* ptr = resource->GetRawPointer();
            size_t size = resource->GetPointerSize();
            if (outSize)
                *outSize = size;
            MMASSETS_LOG("[MM Assets] Loaded from mm.o2r with size: %s -> %p (%zu bytes)", path, ptr, size);
            return ptr;
        }
    }

    MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    return nullptr;
}

/**
 * Load a resource SPECIFICALLY from mm.o2r archive, bypassing the resource cache.
 *
 * CRITICAL: The normal LoadResource() path hits the ResourceManager cache, which may
 * contain OOT versions of resources with the same path (e.g., "audio/fonts/Soundfont_0"
 * exists in both oot.o2r and mm.o2r). By using ResourceIdentifier with the mm.o2r
 * archive as Parent, we get a separate cache entry that loads from mm.o2r specifically.
 *
 * @param path Resource path (e.g., "audio/fonts/Soundfont_0")
 * @param outSize Output: size in bytes (optional, can be NULL)
 * @return Pointer to loaded resource data, or NULL if not found
 */
static void* MmAssets_LoadFromMmArchive(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmArchive || !path) {
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: archive=%p, path=%s", (void*)sMmArchive.get(),
                     path ? path : "NULL");
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: no resource manager");
        return nullptr;
    }

    // Use ResourceIdentifier with explicit Parent archive.
    // This creates a SEPARATE cache key from the default (OOT) version,
    // because the cache hash includes the Parent archive path.
    Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
    auto resource = resourceManager->LoadResource(identifier);
    if (resource) {
        void* ptr = resource->GetRawPointer();
        size_t size = resource->GetPointerSize();
        if (outSize)
            *outSize = size;
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive OK: %s -> %p (%zu bytes)", path, ptr, size);
        return ptr;
    }

    MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: %s not found in mm.o2r", path);
    return nullptr;
}

/**
 * Check if a specific resource exists in mm.o2r
 * Attempts to load the resource and checks if it succeeded
 */
u8 MmAssets_ResourceExists(const char* path) {
    if (!sMmO2rLoaded || path == nullptr) {
        return 0;
    }

    // Try to load and check if it succeeded
    void* resource = MmAssets_LoadResource(path);
    return (resource != nullptr) ? 1 : 0;
}

/**
 * List files matching a pattern from mm.o2r
 * Same as ResourceMgr_ListFiles in 2Ship (load.c lines 1254-1258)
 *
 * @param searchMask Pattern to match (e.g., "audio/fonts*")
 * @param resultSize Output: number of matching files
 * @return Array of file paths (caller must free), or NULL if none found
 */
char** MmAssets_ListFiles(const char* searchMask, int* resultSize) {
    if (!sMmO2rLoaded || searchMask == nullptr || resultSize == nullptr) {
        if (resultSize)
            *resultSize = 0;
        return nullptr;
    }

    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (!archiveManager) {
        *resultSize = 0;
        return nullptr;
    }

    // List files matching pattern from the archive
    // Same pattern as 2Ship's ResourceMgr_ListFiles (BenPort.cpp lines 315-332)
    auto fileList = archiveManager->ListFiles(searchMask);
    if (!fileList || fileList->size() == 0) {
        *resultSize = 0;
        MMASSETS_LOG("[MM Assets] No files match pattern: %s", searchMask);
        return nullptr;
    }

    // Convert to C-style array
    size_t count = fileList->size();
    char** result = (char**)malloc(count * sizeof(char*));
    if (!result) {
        *resultSize = 0;
        return nullptr;
    }

    for (size_t i = 0; i < count; i++) {
        const std::string& path = (*fileList)[i];
        result[i] = (char*)malloc(path.size() + 1);
        if (result[i]) {
            memcpy(result[i], path.c_str(), path.size());
            result[i][path.size()] = '\0';
        }
    }

    *resultSize = (int)count;
    MMASSETS_LOG("[MM Assets] Found %d files matching: %s", (int)count, searchMask);
    return result;
}

// =============================================================================
// Asset Replacement System
// =============================================================================

// MM asset paths for replacements (from mm_sources/archives/)
// Icons (32x32 RGBA from icon_item_static_yar)
#define MM_DEKU_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconDekuMaskTex"
#define MM_STONE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconStoneMaskTex"
#define MM_FIERCE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconFierceDeityMaskTex"

// Name textures (from item_name_static)
#define MM_DEKU_MASK_NAME_PATH "__OTR__item_name_static/gItemNameDekuMaskENGTex"
#define MM_STONE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameStoneMaskENGTex"
#define MM_FIERCE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameFierceDeitysMaskENGTex"

// Get Item DLs (3D models from object_gi_*)
// Each mask has TWO DLs drawn with specific render modes (from 2Ship z_draw.c):
// - Deku: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Stone: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Fierce: GetItem_DrawOpa01 -> FaceDL (Opa) + HairDL (Opa)

// Deku Mask - object_gi_nutsmask
#define MM_DEKU_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskEmptyDL"
#define MM_DEKU_MASK_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskDL"

// Stone Mask - object_gi_stonemask
#define MM_STONE_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskEmptyDL"
#define MM_STONE_MASK_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskDL"

// Fierce Deity - object_gi_mask03 (NOT object_gi_mask18 which is Captain's Hat)
#define MM_FIERCE_MASK_FACE_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskFaceDL"
#define MM_FIERCE_MASK_HAIR_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskHairAndHatDL"

// =============================================================================
// Worn Mask DLs (when Link wears mask on face - DIFFERENT from Get Item DLs!)
// =============================================================================
// These are drawn on Link's face when equipping a mask.
// Transformation masks (Deku, Goron, Zora, Fierce) use gameplay_keep DLs.
// Stone Mask uses its own object file (object_mask_stone).
// From 2Ship z_player_lib.c lines 2918-2926:
//   object_mask_stone_DL_000820,    // PLAYER_MASK_STONE
//   gFierceDeityMaskDL,             // PLAYER_MASK_FIERCE_DEITY (gameplay_keep)
//   gDekuMaskDL,                    // PLAYER_MASK_DEKU (gameplay_keep)

#define MM_DEKU_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gDekuMaskDL"
#define MM_STONE_MASK_WORN_DL_PATH "__OTR__objects/object_mask_stone/object_mask_stone_DL_000820"
#define MM_FIERCE_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gFierceDeityMaskDL"

// Replacement table entry
typedef struct {
    const char* ootPath;  // OOT path (without __OTR__ prefix)
    const char* mmPath;   // MM path (with __OTR__ prefix)
    const char* cvarName; // CVar that controls this replacement
    MmReplaceType type;   // Asset type
} MmAssetReplacementEntry;

// Static replacement table - all transformation mask replacements
static MmAssetReplacementEntry sReplacementTable[] = {
    // =========================================================================
    // Skull Mask → Deku Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSkullTex", MM_DEKU_MASK_ICON_PATH,
      "gMods.TransformMasks.DekuReplacesSkull", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSkullNameTex", MM_DEKU_MASK_NAME_PATH, "gMods.TransformMasks.DekuReplacesSkull",
      MM_REPLACE_TEXT },
    // =========================================================================
    // Spooky Mask → Stone Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSpookyTex", MM_STONE_MASK_ICON_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSpookyNameTex", MM_STONE_MASK_NAME_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_TEXT },
    // =========================================================================
    // Gerudo Mask → Fierce Deity Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskGerudoTex", MM_FIERCE_MASK_ICON_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskGerudoNameTex", MM_FIERCE_MASK_NAME_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_TEXT },
};
static const int sReplacementTableSize = sizeof(sReplacementTable) / sizeof(sReplacementTable[0]);

u8 MmAssets_IsReplacementActive(const char* cvarName) {
    if (!MmAssets_IsAvailable()) {
        return 0;
    }
    if (cvarName == nullptr) {
        return 0;
    }
    // Check CVar value
    return CVarGetInteger(cvarName, 0) ? 1 : 0;
}

const char* MmAssets_GetReplacement(const char* ootPath) {
    if (ootPath == nullptr || !MmAssets_IsAvailable()) {
        return nullptr;
    }

    // Strip __OTR__ prefix if present for comparison
    const char* pathToMatch = ootPath;
    if (strncmp(ootPath, "__OTR__", 7) == 0) {
        pathToMatch = ootPath + 7;
    }

    // Search replacement table
    for (int i = 0; i < sReplacementTableSize; i++) {
        const MmAssetReplacementEntry* entry = &sReplacementTable[i];
        if (strcmp(pathToMatch, entry->ootPath) == 0) {
            // Check if this replacement is active
            if (MmAssets_IsReplacementActive(entry->cvarName)) {
                MMASSETS_LOG("[MM Assets] Replacing %s -> %s", ootPath, entry->mmPath);
                return entry->mmPath;
            }
        }
    }

    return nullptr; // No replacement
}

void* MmAssets_LoadDekuMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskIcon: mm.o2r not available");
        return nullptr;
    }

    void* icon = MmAssets_LoadResource(MM_DEKU_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask icon from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask icon");
    }
    return icon;
}

void* MmAssets_LoadDekuMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskNameText: mm.o2r not available");
        return nullptr;
    }

    void* nameText = MmAssets_LoadResource(MM_DEKU_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask name text from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask name text");
    }
    return nameText;
}

// =============================================================================
// Stone Mask Loaders (replaces Spooky Mask)
// =============================================================================

void* MmAssets_LoadStoneMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* icon = MmAssets_LoadResource(MM_STONE_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask icon from mm.o2r");
    }
    return icon;
}

void* MmAssets_LoadStoneMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* nameText = MmAssets_LoadResource(MM_STONE_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask name text from mm.o2r");
    }
    return nameText;
}

void* MmAssets_LoadStoneMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_STONE_MASK_DL_PATH;
}

// =============================================================================
// Fierce Deity Mask Loaders
// =============================================================================

void* MmAssets_LoadFierceMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_ICON_PATH);
}

void* MmAssets_LoadFierceMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_NAME_PATH);
}

void* MmAssets_LoadFierceMaskFaceDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_FACE_DL_PATH;
}

void* MmAssets_LoadFierceMaskHairDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_HAIR_DL_PATH;
}

// =============================================================================
// Deku Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadDekuMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_EMPTY_DL_PATH;
}

void* MmAssets_LoadDekuMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_DL_PATH;
}

// =============================================================================
// Stone Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadStoneMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_STONE_MASK_EMPTY_DL_PATH;
}

// =============================================================================
// Worn Mask DL Loaders (for Link wearing mask on face)
// =============================================================================
// These DLs are DIFFERENT from Get Item DLs!
// Get Item: object_gi_* files (spinning 3D model when receiving)
// Worn: gameplay_keep or object_mask_* (attached to Link's face)

void* MmAssets_LoadDekuMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Deku Mask WORN DL: %s", MM_DEKU_MASK_WORN_DL_PATH);
    return (void*)MM_DEKU_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadStoneMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Stone Mask WORN DL: %s", MM_STONE_MASK_WORN_DL_PATH);
    return (void*)MM_STONE_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadFierceMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Fierce Deity Mask WORN DL: %s", MM_FIERCE_MASK_WORN_DL_PATH);
    return (void*)MM_FIERCE_MASK_WORN_DL_PATH;
}

// =============================================================================
// MM SFX System - Direct Audio Bypass
// =============================================================================
// Decodes MM ADPCM samples to PCM and mixes directly into OOT's audio output.
// This bypasses OOT's entire SFX pipeline (which caches sound data at startup
// and cannot play injected samples during gameplay).
//
// Architecture:
//   Game thread: MmSfx_PlayAtPos() → decode ADPCM → add to playing list
//   Audio thread: MmDirectAudio_MixInto() → mix PCM into output buffer
// =============================================================================

// MM SFX ID macros (matching OOT's z64audio.h SFX_INDEX)
#define MM_SFX_BANK_SHIFT 12
#define MM_SFX_INDEX_MASK 0x03FF
#define MM_SFX_BANK_INDEX(sfxId) (((sfxId) >> MM_SFX_BANK_SHIFT) & 0xF)
#define MM_SFX_SOUND_INDEX(sfxId) ((sfxId)&MM_SFX_INDEX_MASK)

// MM Goron SFX IDs
#define MM_NA_SE_PL_GORON_ROLL 0x0990
#define MM_NA_SE_PL_GORON_BALL_CHARGE 0x08EB
#define MM_NA_SE_SY_TRANSFORM_MASK_FLASH 0x484F

#define MM_SFX_MAX_FONTS 42 // MM has 41 soundfonts (0-40)
#define MM_SFX_FONT_PATH_FMT "audio/fonts/Soundfont_%d"

// MM SFX sequence (NA_BGM_GENERAL_SFX) uses soundfont 0 as the main SFX font.
// Player/Item/Env/System/Ocarina banks use instruments[]. Voice bank uses soundEffects[] (FONTANY_INSTR_SFX).
// Enemy bank uses Soundfont_1.
static const s32 sMmBankToFontMap[] = { 0, 0, 0, 1, 0, 0, 0 };

// --- Font cache ---
typedef struct {
    s32 fontId;
    SoundFont* font;
    size_t sizeBytes;
} MmSfxCacheEntry;

static MmSfxCacheEntry sSfxCache[MM_SFX_MAX_FONTS];
static s32 sSfxCacheCount = 0;
static s32 sSfxInitialized = 0;
static f32 sTempFreqScale = 1.0f;

static void MmSfxCache_Init(void) {
    if (sSfxInitialized)
        return;
    for (s32 i = 0; i < MM_SFX_MAX_FONTS; i++) {
        sSfxCache[i].fontId = -1;
        sSfxCache[i].font = nullptr;
        sSfxCache[i].sizeBytes = 0;
    }
    sSfxCacheCount = 0;
    sSfxInitialized = 1;
}

static MmSfxCacheEntry* MmSfxCache_Find(s32 fontId) {
    for (s32 i = 0; i < sSfxCacheCount; i++) {
        if (sSfxCache[i].fontId == fontId)
            return &sSfxCache[i];
    }
    return nullptr;
}

static MmSfxCacheEntry* MmSfxCache_GetFree(void) {
    if (sSfxCacheCount < MM_SFX_MAX_FONTS)
        return &sSfxCache[sSfxCacheCount++];
    for (s32 i = 0; i < MM_SFX_MAX_FONTS - 1; i++)
        sSfxCache[i] = sSfxCache[i + 1];
    sSfxCacheCount = MM_SFX_MAX_FONTS - 1;
    return &sSfxCache[sSfxCacheCount++];
}

s32 MmSfx_IsAvailable(void) {
    return MmAssets_IsAvailable();
}

void MmSfx_Init(void) {
    MmSfxCache_Init();
}

void MmSfx_Shutdown(void) {
    MmDirectAudio_StopAll();
    MmSfx_FlushCache();
    sSfxInitialized = 0;
}

SoundFont* MmSfx_LoadFont(s32 fontId) {
    if (!sSfxInitialized)
        MmSfxCache_Init();
    if (fontId < 0 || fontId >= 41) // MM has 41 soundfonts (0-40)
        return nullptr;
    if (!MmAssets_IsAvailable())
        return nullptr;

    MmSfxCacheEntry* cached = MmSfxCache_Find(fontId);
    if (cached && cached->font)
        return cached->font;

    char path[64];
    snprintf(path, sizeof(path), MM_SFX_FONT_PATH_FMT, fontId);

    size_t size = 0;
    void* resource = MmAssets_LoadFromMmArchive(path, &size);
    if (!resource) {
        MMSFX_LOG("[MmSfx] LoadFont FAIL: %s not found in mm.o2r", path);
        return nullptr;
    }

    SoundFont* font = static_cast<SoundFont*>(resource);
    MMSFX_LOG("[MmSfx] LoadFont(%d) OK: %u sfx, %u drums", fontId, font->numSfx, font->numDrums);

    MmSfxCacheEntry* entry = MmSfxCache_GetFree();
    if (entry) {
        entry->fontId = fontId;
        entry->font = font;
        entry->sizeBytes = size;
    }
    return font;
}

SoundFont* MmSfx_GetFontForSfx(u16 sfxId) {
    s32 bank = MM_SFX_BANK_INDEX(sfxId);
    if (bank < 0 || bank >= 7)
        return nullptr;
    return MmSfx_LoadFont(sMmBankToFontMap[bank]);
}

// =============================================================================
// Direct Audio: ADPCM Decoder
// =============================================================================
// Decodes N64 VADPCM (codec 0) and SMALL_ADPCM (codec 3) to s16 PCM.
// Algorithm: Block-based prediction using codebook (order=2, 8-sample sub-frames).

#define VADPCM_FRAME_ADPCM 9       // codec 0: 1 header + 8 data bytes
#define VADPCM_FRAME_SMALL_ADPCM 5 // codec 3: 1 header + 4 data bytes
#define VADPCM_SAMPLES_PER_FRAME 16

// Decode one ADPCM frame (16 samples)
// Algorithm matches soh/soh/mixer.c aADPCMdecImpl() exactly
static void MmDirectAudio_DecodeFrame(const u8* frame, s32 frameSize, s16* out, const s16* book, s32 order, s16* hist) {
    s32 shift = frame[0] >> 4;
    s32 pred = frame[0] & 0xF;
    const s16* tbl0 = &book[pred * order * 8];     // coefs for prev2
    const s16* tbl1 = &book[pred * order * 8 + 8]; // coefs for prev1
    const u8* data = &frame[1];

    // Extract and scale input nibbles per sub-frame (matching mixer.c)
    for (s32 half = 0; half < 2; half++) {
        s16 ins[8];
        s16 prev1 = hist[1]; // most recent
        s16 prev2 = hist[0]; // second most recent

        if (frameSize == VADPCM_FRAME_SMALL_ADPCM) {
            // codec 3: 2 bits per sample, 2 bytes per sub-frame
            const u8* p = &data[half * 2];
            for (s32 j = 0; j < 2; j++) {
                ins[j * 4] = (s16)(((s32)(p[j] >> 6) << 30) >> 30) << shift;
                ins[j * 4 + 1] = (s16)((((s32)(p[j] >> 4) & 0x3) << 30) >> 30) << shift;
                ins[j * 4 + 2] = (s16)((((s32)(p[j] >> 2) & 0x3) << 30) >> 30) << shift;
                ins[j * 4 + 3] = (s16)((((s32)(p[j]) & 0x3) << 30) >> 30) << shift;
            }
        } else {
            // codec 0: 4 bits per sample, 4 bytes per sub-frame
            const u8* p = &data[half * 4];
            for (s32 j = 0; j < 4; j++) {
                ins[j * 2] = (s16)(((s32)(p[j] >> 4) << 28) >> 28) << shift;
                ins[j * 2 + 1] = (s16)((((s32)(p[j]) & 0xF) << 28) >> 28) << shift;
            }
        }

        // Core prediction loop - RECURSIVE within sub-frame (matching mixer.c:220-227)
        for (s32 j = 0; j < 8; j++) {
            s32 acc = tbl0[j] * prev2 + tbl1[j] * prev1 + ((s32)ins[j] << 11);
            for (s32 k = 0; k < j; k++) {
                acc += tbl1[((j - k) - 1)] * ins[k];
            }
            acc >>= 11;
            if (acc > 32767)
                acc = 32767;
            if (acc < -32768)
                acc = -32768;
            out[half * 8 + j] = (s16)acc;
        }

        // Update history for next sub-frame
        hist[0] = out[half * 8 + 6]; // second most recent
        hist[1] = out[half * 8 + 7]; // most recent
    }
}

// Decode entire ADPCM sample to PCM buffer
static s16* MmDirectAudio_DecodeADPCM(SoundFontSample* sample, u32* outLength) {
    if (!sample || !sample->sampleAddr || sample->size == 0)
        return nullptr;

    s32 frameSize;
    switch (sample->codec) {
        case 0:
            frameSize = VADPCM_FRAME_ADPCM;
            break;
        case 3:
            frameSize = VADPCM_FRAME_SMALL_ADPCM;
            break;
        default:
            MMSFX_LOG("[MmDirectAudio] Unsupported codec %d", sample->codec);
            return nullptr;
    }

    if (!sample->book || !sample->book->book) {
        MMSFX_LOG("[MmDirectAudio] No codebook for sample");
        return nullptr;
    }

    u32 numFrames = sample->size / frameSize;
    u32 totalSamples = numFrames * VADPCM_SAMPLES_PER_FRAME;

    // Limit to loop end if looping
    if (sample->loop && sample->loop->loopEnd > 0 && sample->loop->loopEnd < totalSamples) {
        totalSamples = sample->loop->loopEnd;
        numFrames = (totalSamples + VADPCM_SAMPLES_PER_FRAME - 1) / VADPCM_SAMPLES_PER_FRAME;
    }

    s16* pcm = (s16*)malloc(totalSamples * sizeof(s16));
    if (!pcm)
        return nullptr;

    s16 hist[2] = { 0, 0 };
    const u8* src = (const u8*)sample->sampleAddr;
    s32 order = sample->book->order;
    const s16* book = sample->book->book;

    for (u32 f = 0; f < numFrames; f++) {
        s16 frameBuf[VADPCM_SAMPLES_PER_FRAME];
        MmDirectAudio_DecodeFrame(&src[f * frameSize], frameSize, frameBuf, book, order, hist);

        u32 dstOffset = f * VADPCM_SAMPLES_PER_FRAME;
        u32 count = VADPCM_SAMPLES_PER_FRAME;
        if (dstOffset + count > totalSamples) {
            count = totalSamples - dstOffset;
        }
        memcpy(&pcm[dstOffset], frameBuf, count * sizeof(s16));
    }

    *outLength = totalSamples;
    return pcm;
}

// =============================================================================
// Direct Audio: Playing Sound List + Mixer
// =============================================================================

#define MM_DIRECT_MAX_SOUNDS 8

typedef struct {
    s16* pcmData;    // Decoded PCM buffer (allocated, must be freed)
    u32 pcmLength;   // Total samples in buffer
    f32 pcmPosition; // Current fractional playback position
    f32 advance;     // Samples to advance per output sample (tuning * freqScale)
    f32 volume;      // Volume [0..1]
    f32 pan;         // Pan [0=left, 0.5=center, 1=right]
    u16 mmSfxId;     // MM SFX ID for stop/identify
    u8 active;       // 1=playing, 0=free
} MmPlayingSound;

static MmPlayingSound sPlayingSounds[MM_DIRECT_MAX_SOUNDS];

// =============================================================================
// SFX → Instrument Mapping Table (derived from seq_0.prg.seq analysis)
// =============================================================================
// In MM, SFX IDs do NOT index directly into soundEffects[] or drums[].
// They go through the SFX sequence (seq_0) which selects specific instruments
// from Soundfont_0 and plays them at specific pitches.
//
// This table maps each known Goron SFX to its primary instrument and note,
// giving us the correct sample with correct pitch - matching MM 1:1.

typedef struct {
    u16 sfxId;        // MM SFX ID (with SFX_FLAG)
    u8 instrumentIdx; // Index into font->instruments[] (Soundfont_0)
    u8 midiNote;      // MIDI note number for pitch calculation
} MmSfxInstrMapEntry;

// Mapping from seq_0.prg.seq channel handlers (primary layer of each SFX)
static const MmSfxInstrMapEntry sMmSfxInstrMap[] = {
    // === Player Bank: Common SFX (shared by all forms) ===
    { 0x0811, 0, 49 },  // JUMP: INST_0, PITCH_CS3
    { 0x0812, 0, 61 },  // LAND: INST_0, PITCH_CS4
    { 0x0814, 9, 66 },  // CLIMB_CLIFF: INST_9, PITCH_FS4
    { 0x08D0, 12, 60 }, // SLIP_LEVEL: INST_12, PITCH_C4
    // === Player Bank: Deku SFX ===
    { 0x08E0, 74, 49 }, // DEKUNUTS_FIRE: INST_74, PITCH_E3 (bubble spit)
    // === Player Bank: Goron SFX ===
    { 0x08E1, 102, 55 }, // GORON_BALLJUMP: INST_102, PITCH_G3
    { 0x08E4, 68, 78 },  // TRANSFORM: INST_68, PITCH_GF5 (primary of 3 layers)
    { 0x08E5, 47, 55 },  // TRANSFORM_DEMO: INST_47, PITCH_G3
    { 0x08E6, 47, 55 },  // GORON_TO_BALL: INST_47 (same channel as TRANSFORM_DEMO)
    { 0x08E7, 47, 35 },  // BALL_TO_GORON: INST_47, PITCH_B1
    { 0x08E8, 65, 53 },  // GORON_PUNCH: INST_65, PITCH_F3 (primary of 2 layers)
    { 0x08EB, 35, 65 },  // GORON_BALL_CHARGE: INST_35, PITCH_F4 (primary, looping)
    // === Player Bank: Zora SFX ===
    { 0x08EC, 20, 73 },  // ZORA_SWIM_DASH: INST_20, PITCH_DF5
    { 0x08ED, 72, 38 },  // ZORA_SWIM_LV: INST_72, PITCH_F2
    { 0x08EE, 105, 28 }, // ZORA_SWIM_ROLL: INST_105, PITCH_E2
    { 0x08EF, 47, 35 },  // GORON_SQUAT: INST_47, PITCH_B1
    // === Player Bank: Zora SFX (0x8F0 range - CHAN_PL_DUMMY_240) ===
    { 0x08F0, 31, 23 }, // ZORA_SWIM: INST_31, PITCH_B0 (CHAN_PL_DUMMY_240 primary)
    { 0x08F1, 31, 23 }, // ZORA_KICK: INST_31, PITCH_B0 (same channel)
    { 0x08F2, 31, 23 }, // ZORA_DIVE: INST_31, PITCH_B0 (same channel)
    { 0x08F3, 31, 23 }, // ZORA_ELECTRIC_BARRIER: INST_31, PITCH_B0 (same channel)
    { 0x08F4, 31, 23 }, // ZORA_BOOMERANG_THROW: INST_31, PITCH_B0 (same channel)
    { 0x08F5, 31, 23 }, // ZORA_BOOMERANG_CATCH: INST_31, PITCH_B0 (same channel)
    // === Player Bank: Goron roll SFX ===
    { 0x0980, 35, 67 }, // GORON_CHG_ROLL: INST_35, PITCH_G4
    { 0x0990, 77, 58 }, // GORON_ROLL: INST_77, PITCH_BF3 (primary of 3 layers)
    // === Player Bank: Deku SFX (0x9A0 range) ===
    { 0x09A1, 74, 54 },  // DEKUNUTS_BUBLE_BREATH: INST_74, PITCH_A3 (looping)
    { 0x09A2, 35, 36 },  // GORON_BALL_CHARGE_FAILED: INST_35, PITCH_C2
    { 0x09A3, 75, 71 },  // GORON_BALL_CHARGE_DASH: INST_75, PITCH_B4
    { 0x09A9, 27, 24 },  // DEKUNUTS_ATTACK: INST_27, PITCH_C1 (spin attack)
    { 0x09AD, 111, 60 }, // GORON_SLIP: INST_111, PITCH_C4 (looping)
    { 0x09AF, 46, 63 },  // ZORA_SPARK_BARRIER: INST_46, PITCH_E4
    { 0x09B8, 77, 77 },  // GORON_STOMACH_EXPLOSION: INST_77, PITCH_F5
    { 0x09B9, 106, 47 }, // GORON_DRINK_BOMB: INST_106, PITCH_B2
    // === Item Bank: Form-specific ===
    { 0x184F, 32, 60 },  // IT_GORON_BALLFANG: INST_32, PITCH_C4
    { 0x1857, 27, 24 },  // IT_GORON_PUNCH_SWING: INST_27, PITCH_C1
    { 0x1859, 39, 42 },  // IT_ZORA_KICK_SWING: INST_39, PITCH_GF2
    { 0x185E, 102, 45 }, // IT_GORON_ROLLING_REFLECTION: INST_102, PITCH_A2
    // === System Bank: Transform flash ===
    { 0x484F, 64, 84 }, // SY_TRANSFORM_MASK_FLASH: INST_64, C4+24 transpose
    { 0x4835, 64, 84 }, // (legacy ID - same sound)
};
static const s32 sMmSfxInstrMapSize = sizeof(sMmSfxInstrMap) / sizeof(sMmSfxInstrMap[0]);

// =============================================================================
// Voice Bank: Goron voices = Human Link voices with transpose +4
// =============================================================================
// From seq_0.prg.seq: Goron voice channels (DUMMY_192-223) call CHAN_BD84
// which sets transpose=4, then jump to the corresponding human Link voice
// channel. The voice channels use FONTANY_INSTR_SFX mode which indexes into
// font->soundEffects[].
//
// For voices with directly defined effect indices (from seq_0):
typedef struct {
    u16 sfxId;     // MM Voice SFX ID
    u16 effectIdx; // SF0_EFFECT_X index into soundEffects[]
    s8 transpose;  // Semitone transpose (4 for Goron, 1 for some others)
} MmVoiceMapEntry;

static const MmVoiceMapEntry sMmVoiceMap[] = {
    // Directly defined in seq_0 with explicit SF0_EFFECT indices:
    { 0x68CA, 23, 4 }, // DUMMY_202 (GORON_DOWN alt): SF0_EFFECT_23, transpose 4
    { 0x68CB, 20, 4 }, // DUMMY_203 (GORON_DOWN): SF0_EFFECT_20, transpose 4
    { 0x68D0, 17, 4 }, // DUMMY_208: SF0_EFFECT_17, transpose 4 (looping)
    { 0x68D8, 6, 4 },  // DUMMY_216: SF0_EFFECT_6, transpose 4
    { 0x68DA, 24, 4 }, // DUMMY_218: SF0_EFFECT_24, transpose 4
    { 0x68E1, 35, 1 }, // DUMMY_225: SF0_EFFECT_35, transpose 1
    { 0x68E5, 36, 1 }, // DUMMY_229: SF0_EFFECT_36, transpose 1
};
static const s32 sMmVoiceMapSize = sizeof(sMmVoiceMap) / sizeof(sMmVoiceMap[0]);

// =============================================================================
// Goron voice → human Link voice redirect table
// =============================================================================
// Goron voices (0x68C0-0x68DF) that redirect to human Link voice channels
// via CHAN_BD84 (transpose +4). The human Link voices are at bank 6 offset 0x00.
// Each Goron voice index maps to a human Link voice that uses a specific
// SF0_EFFECT. These effect indices were traced from seq_0 channel handlers.
//
// Human Link voice channels and their SF0_EFFECT indices:
//   LI_SWORD_N  → effect 0    LI_SWORD_L  → effect 1
//   LI_LASH     → effect 2    LI_HANG     → effect 3
//   LI_CLIMB_END→ effect 4    LI_DAMAGE_S → effect 5
//   LI_FREEZE   → effect 6    LI_FALL_S   → effect 7
//   LI_FALL_L   → effect 8    LI_BREATH_REST→ effect 9
//
// Goron voices at 0x68C0-0x68C9 map to human Link voices 0-9:
static const s32 sGoronVoiceToEffect[] = {
    0, // 0x68C0 GORON_SWORD_N  → LI_SWORD_N  → SF0_EFFECT_0
    1, // 0x68C1 GORON_SWORD_L  → LI_SWORD_L  → SF0_EFFECT_1
    0, // 0x68C2 GORON_LASH     → LI_SWORD_N  → SF0_EFFECT_0 (same as DUMMY_192)
    3, // 0x68C3 GORON_HANG     → LI_HANG     → SF0_EFFECT_3
    4, // 0x68C4 GORON_CLIMB_END→ LI_CLIMB_END→ SF0_EFFECT_4
    5, // 0x68C5 GORON_DAMAGE_S → LI_DAMAGE_S → SF0_EFFECT_5
    6, // 0x68C6 GORON_FREEZE   → LI_FREEZE   → SF0_EFFECT_6
    7, // 0x68C7 GORON_FALL_S   → LI_FALL_S   → SF0_EFFECT_7
    8, // 0x68C8 GORON_FALL_L   → LI_FALL_L   → SF0_EFFECT_8
    9, // 0x68C9 GORON_BREATH_REST→LI_BREATH_REST→SF0_EFFECT_9
};
static const s32 sGoronVoiceToEffectSize = sizeof(sGoronVoiceToEffect) / sizeof(sGoronVoiceToEffect[0]);

// Pitch factor for semitone transpose: 2^(semitones/12)
static f32 MmDirectAudio_TransposeFactor(s32 semitones) {
    // Fast lookup for common values
    if (semitones == 0)
        return 1.0f;
    if (semitones == 4)
        return 1.259921f; // 2^(4/12) - Goron voice pitch
    if (semitones == 1)
        return 1.059463f; // 2^(1/12)
    // General case
    return powf(2.0f, (f32)semitones / 12.0f);
}

// Helper: check if a SoundFontSound has a valid sample loaded
static inline bool MmDirectAudio_SoundValid(SoundFontSound* s) {
    return s && s->sample && s->sample->sampleAddr;
}

// Get SoundFontSound from an instrument at a specific MIDI note.
// Many MM instruments only populate normalNotesSound, leaving low/high splits NULL.
// If the MIDI note selects a split with no sample, we fall back to any valid split.
static SoundFontSound* MmDirectAudio_GetInstrumentSound(SoundFont* font, u8 instrumentIdx, u8 midiNote) {
    if (!font || !font->instruments)
        return nullptr;
    if (instrumentIdx >= font->numInstruments)
        return nullptr;

    Instrument* inst = font->instruments[instrumentIdx];
    if (!inst || !inst->loaded)
        return nullptr;

    // Select the correct pitch split based on MIDI note
    SoundFontSound* sound;
    if (midiNote < inst->normalRangeLo) {
        sound = &inst->lowNotesSound;
    } else if (midiNote <= inst->normalRangeHi) {
        sound = &inst->normalNotesSound;
    } else {
        sound = &inst->highNotesSound;
    }

    // If the selected split has a valid sample, use it
    if (MmDirectAudio_SoundValid(sound))
        return sound;

    // Fallback: most instruments only populate normalNotesSound.
    // Try normalNotesSound first (most common), then low, then high.
    if (MmDirectAudio_SoundValid(&inst->normalNotesSound))
        return &inst->normalNotesSound;
    if (MmDirectAudio_SoundValid(&inst->lowNotesSound))
        return &inst->lowNotesSound;
    if (MmDirectAudio_SoundValid(&inst->highNotesSound))
        return &inst->highNotesSound;

    return nullptr;
}

// Stored pitch scale for the most recent GetSound call
static f32 sMmLastPitchScale = 1.0f;

// Get SoundFontSound for an MM SFX ID with correct instrument/effect mapping
static SoundFontSound* MmDirectAudio_GetSound(u16 mmSfxId) {
    s32 bank = MM_SFX_BANK_INDEX(mmSfxId);
    s32 sfxIndex = MM_SFX_SOUND_INDEX(mmSfxId);
    sMmLastPitchScale = 1.0f;

    SoundFont* font0 = MmSfx_LoadFont(0); // Soundfont_0 - main SFX font
    if (!font0) {
        MMSFX_LOG("[MmDirectAudio] Failed to load Soundfont_0");
        return nullptr;
    }

    // =========================================================================
    // Voice bank (6): uses soundEffects[] in FONTANY_INSTR_SFX mode
    // Goron voices = human Link voices with transpose +4 semitones
    // =========================================================================
    if (bank == 6) {
        // First check the explicit voice map (directly-defined effect indices)
        for (s32 i = 0; i < sMmVoiceMapSize; i++) {
            if (sMmVoiceMap[i].sfxId == mmSfxId) {
                u16 effectIdx = sMmVoiceMap[i].effectIdx;
                if (effectIdx < font0->numSfx && font0->soundEffects[effectIdx].sample &&
                    font0->soundEffects[effectIdx].sample->sampleAddr) {
                    sMmLastPitchScale = MmDirectAudio_TransposeFactor(sMmVoiceMap[i].transpose);
                    MMSFX_LOG("[MmDirectAudio] Voice 0x%04X: soundEffects[%d], transpose %d (pitch %.3f)", mmSfxId,
                              effectIdx, sMmVoiceMap[i].transpose, sMmLastPitchScale);
                    return &font0->soundEffects[effectIdx];
                }
            }
        }

        // Goron voice redirect: 0x68C0-0x68C9 → human Link voices with transpose +4
        if (mmSfxId >= 0x68C0 && mmSfxId < 0x68C0 + (u16)sGoronVoiceToEffectSize) {
            s32 goronIdx = mmSfxId - 0x68C0;
            s32 effectIdx = sGoronVoiceToEffect[goronIdx];
            if (effectIdx >= 0 && (u32)effectIdx < font0->numSfx && font0->soundEffects[effectIdx].sample &&
                font0->soundEffects[effectIdx].sample->sampleAddr) {
                sMmLastPitchScale = MmDirectAudio_TransposeFactor(4); // Goron transpose +4
                MMSFX_LOG("[MmDirectAudio] Goron voice 0x%04X: soundEffects[%d], transpose +4", mmSfxId, effectIdx);
                return &font0->soundEffects[effectIdx];
            }
        }

        // Remaining Goron voices (0x68CA-0x68DF) not in explicit map:
        // Try mapping by offset from 0x68C0 to soundEffects index
        if (mmSfxId >= 0x68C0 && mmSfxId <= 0x68DF) {
            s32 offset = mmSfxId - 0x68C0;
            // These voices redirect to various human Link voices
            // Use the offset as a best-effort effect index
            if ((u32)offset < font0->numSfx && font0->soundEffects[offset].sample &&
                font0->soundEffects[offset].sample->sampleAddr) {
                sMmLastPitchScale = MmDirectAudio_TransposeFactor(4);
                MMSFX_LOG("[MmDirectAudio] Goron voice 0x%04X: soundEffects[%d] (offset fallback), transpose +4",
                          mmSfxId, offset);
                return &font0->soundEffects[offset];
            }
        }

        // Non-Goron voices: use sfxIndex as effect index (human Link, Zora, etc.)
        if ((u32)sfxIndex < font0->numSfx && font0->soundEffects[sfxIndex].sample &&
            font0->soundEffects[sfxIndex].sample->sampleAddr) {
            MMSFX_LOG("[MmDirectAudio] Voice 0x%04X: soundEffects[%d] (direct index)", mmSfxId, sfxIndex);
            return &font0->soundEffects[sfxIndex];
        }

        MMSFX_LOG("[MmDirectAudio] Voice: No valid soundEffect for 0x%04X (sfxIndex=%d, numSfx=%d)", mmSfxId, sfxIndex,
                  font0->numSfx);
        return nullptr;
    }

    // =========================================================================
    // Player/Item/Environment/System/Ocarina banks:
    // SFX IDs map to specific instruments[] at specific pitches via seq_0
    // =========================================================================

    // Check the instrument mapping table first
    for (s32 i = 0; i < sMmSfxInstrMapSize; i++) {
        if (sMmSfxInstrMap[i].sfxId == mmSfxId) {
            u8 instIdx = sMmSfxInstrMap[i].instrumentIdx;
            u8 note = sMmSfxInstrMap[i].midiNote;
            SoundFontSound* sound = MmDirectAudio_GetInstrumentSound(font0, instIdx, note);
            if (sound) {
                // Pitch correction: the tuning is calibrated for MIDI note 60 (middle C)
                // Adjust for the actual note
                sMmLastPitchScale = powf(2.0f, ((f32)note - 60.0f) / 12.0f);
                MMSFX_LOG("[MmDirectAudio] Mapped 0x%04X: instruments[%d], note=%d, pitch=%.3f", mmSfxId, instIdx, note,
                          sMmLastPitchScale);
                return sound;
            }
            MMSFX_LOG("[MmDirectAudio] Mapped 0x%04X: instruments[%d] exists but no valid sample", mmSfxId, instIdx);
            break;
        }
    }

    // SFX not found in instrument map - return NULL (silence).
    // DO NOT use soundEffects[sfxIndex] as fallback - SFX IDs do not map to soundEffects
    // indices for non-voice banks. The seq_0 program routes them to specific instruments
    // at specific pitches. Without a mapping entry, we'd play the wrong sound.
    MMSFX_LOG("[MmDirectAudio] No mapping for 0x%04X (bank=%d, idx=%d) - no sound", mmSfxId, bank, sfxIndex);
    return nullptr;
}

// Start playing an MM sound. Returns 1 if played, 0 if no valid sample found.
static s32 MmDirectAudio_Play(u16 mmSfxId, f32 freqScale) {
    SoundFontSound* sfxSound = MmDirectAudio_GetSound(mmSfxId);
    f32 pitchScale = sMmLastPitchScale; // Saved by GetSound
    if (!sfxSound || !sfxSound->sample) {
        MMSFX_LOG("[MmDirectAudio] No sample for 0x%04X", mmSfxId);
        return 0;
    }

    u32 pcmLength = 0;
    s16* pcm = MmDirectAudio_DecodeADPCM(sfxSound->sample, &pcmLength);
    if (!pcm || pcmLength == 0) {
        MMSFX_LOG("[MmDirectAudio] Decode failed for 0x%04X", mmSfxId);
        return 0;
    }

    // Find free slot (or evict oldest)
    s32 freeSlot = -1;
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        if (!sPlayingSounds[i].active) {
            freeSlot = i;
            break;
        }
    }
    if (freeSlot < 0) {
        freeSlot = 0;
        if (sPlayingSounds[0].pcmData)
            free(sPlayingSounds[0].pcmData);
        sPlayingSounds[0].pcmData = nullptr;
        sPlayingSounds[0].active = 0;
    }

    MmPlayingSound* snd = &sPlayingSounds[freeSlot];
    if (snd->pcmData)
        free(snd->pcmData);

    snd->pcmData = pcm;
    snd->pcmLength = pcmLength;
    snd->pcmPosition = 0.0f;
    // Apply both the sample's base tuning, pitch correction for the note, and user freq scale
    snd->advance = sfxSound->tuning * pitchScale * freqScale;
    snd->volume = 0.8f;
    snd->pan = 0.5f;
    snd->mmSfxId = mmSfxId;
    snd->active = 1;

    MMSFX_LOG("[MmDirectAudio] Playing 0x%04X: %u samples, tuning=%.3f, pitch=%.3f, freq=%.3f, advance=%.3f", mmSfxId,
              pcmLength, sfxSound->tuning, pitchScale, freqScale, snd->advance);
    return 1;
}

// Mix all active MM sounds into the output buffer (called from audio thread)
// outBuf: interleaved stereo s16 [L0,R0,L1,R1,...], numSamples = stereo pairs
void MmDirectAudio_MixInto(s16* outBuf, u32 numSamples) {
    for (s32 slot = 0; slot < MM_DIRECT_MAX_SOUNDS; slot++) {
        MmPlayingSound* snd = &sPlayingSounds[slot];
        if (!snd->active || !snd->pcmData)
            continue;

        f32 volL = snd->volume * (1.0f - snd->pan);
        f32 volR = snd->volume * snd->pan;

        for (u32 i = 0; i < numSamples; i++) {
            u32 pos = (u32)snd->pcmPosition;
            if (pos >= snd->pcmLength - 1) {
                snd->active = 0;
                break;
            }

            // Linear interpolation between adjacent samples
            f32 frac = snd->pcmPosition - (f32)pos;
            f32 sample = snd->pcmData[pos] * (1.0f - frac) + snd->pcmData[pos + 1] * frac;

            s32 outL = outBuf[i * 2] + (s32)(sample * volL);
            s32 outR = outBuf[i * 2 + 1] + (s32)(sample * volR);

            if (outL > 32767)
                outL = 32767;
            if (outL < -32768)
                outL = -32768;
            if (outR > 32767)
                outR = 32767;
            if (outR < -32768)
                outR = -32768;

            outBuf[i * 2] = (s16)outL;
            outBuf[i * 2 + 1] = (s16)outR;

            snd->pcmPosition += snd->advance;
        }
    }
}

// Stop a specific MM sound
static void MmDirectAudio_StopById(u16 mmSfxId) {
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        if (sPlayingSounds[i].active && sPlayingSounds[i].mmSfxId == mmSfxId) {
            sPlayingSounds[i].active = 0;
        }
    }
}

// Stop all MM sounds and free PCM buffers
void MmDirectAudio_StopAll(void) {
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        sPlayingSounds[i].active = 0;
        if (sPlayingSounds[i].pcmData) {
            free(sPlayingSounds[i].pcmData);
            sPlayingSounds[i].pcmData = nullptr;
        }
    }
}

// =============================================================================
// MmSfx Public API (unchanged interface, new direct audio backend)
// =============================================================================

s32 MmSfx_PlayAtPos(u16 sfxId, Vec3f* pos) {
    return MmSfx_PlayEx(sfxId, pos, 4, nullptr, nullptr, nullptr);
}

s32 MmSfx_PlayEx(u16 sfxId, Vec3f* pos, u8 token, f32* freqScale, f32* vol, s8* reverbAdd) {
    if (!MmAssets_IsAvailable())
        return 0;
    f32 freq = freqScale ? *freqScale : 1.0f;
    return MmDirectAudio_Play(sfxId, freq);
}

void MmSfx_Stop(u16 sfxId) {
    MmDirectAudio_StopById(sfxId);
}

void MmSfx_PlayGoronRoll(Vec3f* pos, f32 speed) {
    sTempFreqScale = 0.8f + (speed / 20.0f) * 0.4f;
    if (sTempFreqScale > 1.5f)
        sTempFreqScale = 1.5f;
    if (sTempFreqScale < 0.5f)
        sTempFreqScale = 0.5f;
    MmSfx_PlayEx(MM_NA_SE_PL_GORON_ROLL, pos, 4, &sTempFreqScale, nullptr, nullptr);
}

void MmSfx_PlayGoronCharge(Vec3f* pos, f32 chargeLevel) {
    sTempFreqScale = 0.7f + chargeLevel * 0.6f;
    MmSfx_PlayEx(MM_NA_SE_PL_GORON_BALL_CHARGE, pos, 4, &sTempFreqScale, nullptr, nullptr);
}

void MmSfx_PlayTransformFlash(void) {
    MmSfx_PlayAtPos(MM_NA_SE_SY_TRANSFORM_MASK_FLASH, nullptr);
}

void MmSfx_GetCacheStats(s32* outLoadedFonts, s32* outTotalBytes) {
    if (outLoadedFonts)
        *outLoadedFonts = sSfxCacheCount;
    if (outTotalBytes) {
        size_t total = 0;
        for (s32 i = 0; i < sSfxCacheCount; i++)
            total += sSfxCache[i].sizeBytes;
        *outTotalBytes = (s32)total;
    }
}

void MmSfx_FlushCache(void) {
    for (s32 i = 0; i < MM_SFX_MAX_FONTS; i++) {
        sSfxCache[i].fontId = -1;
        sSfxCache[i].font = nullptr;
        sSfxCache[i].sizeBytes = 0;
    }
    sSfxCacheCount = 0;
}

// =============================================================================
// MM Masks Inventory: Icon and Name Texture Loaders (24 masks)
// =============================================================================
// Paths verified from MM decomp: extracted/n64-us/assets/archives/icon_item_static/icon_item_static_yar.h
// and item_name_static/item_name_static.h

// Icon paths (32x32 RGBA textures from icon_item_static_yar)
static const char* sMmMaskIconPaths[24] = {
    "__OTR__icon_item_static_yar/gItemIconPostmansHatTex",      // 0: Postman's Hat
    "__OTR__icon_item_static_yar/gItemIconAllNightMaskTex",     // 1: All-Night Mask
    "__OTR__icon_item_static_yar/gItemIconBlastMaskTex",        // 2: Blast Mask
    "__OTR__icon_item_static_yar/gItemIconStoneMaskTex",        // 3: Stone Mask
    "__OTR__icon_item_static_yar/gItemIconGreatFairyMaskTex",   // 4: Great Fairy Mask
    "__OTR__icon_item_static_yar/gItemIconDekuMaskTex",         // 5: Deku Mask
    "__OTR__icon_item_static_yar/gItemIconKeatonMaskTex",       // 6: Keaton Mask
    "__OTR__icon_item_static_yar/gItemIconBremenMaskTex",       // 7: Bremen Mask
    "__OTR__icon_item_static_yar/gItemIconBunnyHoodTex",        // 8: Bunny Hood
    "__OTR__icon_item_static_yar/gItemIconDonGeroMaskTex",      // 9: Don Gero's Mask
    "__OTR__icon_item_static_yar/gItemIconMaskOfScentsTex",     // 10: Mask of Scents
    "__OTR__icon_item_static_yar/gItemIconGoronMaskTex",        // 11: Goron Mask
    "__OTR__icon_item_static_yar/gItemIconRomaniMaskTex",       // 12: Romani's Mask
    "__OTR__icon_item_static_yar/gItemIconCircusLeaderMaskTex", // 13: Circus Leader's Mask
    "__OTR__icon_item_static_yar/gItemIconKafeisMaskTex",       // 14: Kafei's Mask
    "__OTR__icon_item_static_yar/gItemIconCouplesMaskTex",      // 15: Couple's Mask
    "__OTR__icon_item_static_yar/gItemIconMaskOfTruthTex",      // 16: Mask of Truth
    "__OTR__icon_item_static_yar/gItemIconZoraMaskTex",         // 17: Zora Mask
    "__OTR__icon_item_static_yar/gItemIconKamaroMaskTex",       // 18: Kamaro's Mask
    "__OTR__icon_item_static_yar/gItemIconGibdoMaskTex",        // 19: Gibdo Mask
    "__OTR__icon_item_static_yar/gItemIconGaroMaskTex",         // 20: Garo Mask
    "__OTR__icon_item_static_yar/gItemIconCaptainsHatTex",      // 21: Captain's Hat
    "__OTR__icon_item_static_yar/gItemIconGiantsMaskTex",       // 22: Giant's Mask
    "__OTR__icon_item_static_yar/gItemIconFierceDeityMaskTex",  // 23: Fierce Deity Mask
};

// Name texture paths (from item_name_static)
static const char* sMmMaskNamePaths[24] = {
    "__OTR__item_name_static/gItemNamePostmansHatENGTex",
    "__OTR__item_name_static/gItemNameAllNightMaskENGTex",
    "__OTR__item_name_static/gItemNameBlastMaskENGTex",
    "__OTR__item_name_static/gItemNameStoneMaskENGTex",
    "__OTR__item_name_static/gItemNameGreatFairysMaskENGTex",
    "__OTR__item_name_static/gItemNameDekuMaskENGTex",
    "__OTR__item_name_static/gItemNameKeatonMaskENGTex",
    "__OTR__item_name_static/gItemNameBremenMaskENGTex",
    "__OTR__item_name_static/gItemNameBunnyHoodENGTex",
    "__OTR__item_name_static/gItemNameDonGerosMaskENGTex",
    "__OTR__item_name_static/gItemNameMaskOfScentsENGTex",
    "__OTR__item_name_static/gItemNameGoronMaskENGTex",
    "__OTR__item_name_static/gItemNameRomanisMaskENGTex",
    "__OTR__item_name_static/gItemNameCircusLeadersMaskENGTex",
    "__OTR__item_name_static/gItemNameKafeisMaskENGTex",
    "__OTR__item_name_static/gItemNameCouplesMaskENGTex",
    "__OTR__item_name_static/gItemNameMaskOfTruthENGTex",
    "__OTR__item_name_static/gItemNameZoraMaskENGTex",
    "__OTR__item_name_static/gItemNameKamarosMaskENGTex",
    "__OTR__item_name_static/gItemNameGibdoMaskENGTex",
    "__OTR__item_name_static/gItemNameGarosMaskENGTex",
    "__OTR__item_name_static/gItemNameCaptainsHatENGTex",
    "__OTR__item_name_static/gItemNameGiantsMaskENGTex",
    "__OTR__item_name_static/gItemNameFierceDeitysMaskENGTex",
};

// Cached icon pointers (NULL = not yet loaded)
static void* sCachedMaskIcons[24] = { 0 };
static bool sMaskIconLoaded[24] = { false };

// Cached name texture pointers
static void* sCachedMaskNames[24] = { 0 };
static bool sMaskNameLoaded[24] = { false };

// ITEM_MM_MASK_POSTMAN = 0xB7, so index = itemId - 0xB7
#define MM_MASK_ITEM_BASE 0xB7

void* MmMasks_LoadIcon(uint16_t itemId) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;

    int idx = itemId - MM_MASK_ITEM_BASE;
    if (sMaskIconLoaded[idx])
        return sCachedMaskIcons[idx];

    sMaskIconLoaded[idx] = true;
    sCachedMaskIcons[idx] = MmAssets_LoadResource(sMmMaskIconPaths[idx]);
    if (sCachedMaskIcons[idx]) {
        MMASSETS_LOG("[MM Masks] Loaded icon %d: %s", idx, sMmMaskIconPaths[idx]);
    }
    return sCachedMaskIcons[idx];
}

void* MmMasks_LoadNameTex(uint16_t itemId) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (itemId < MM_MASK_ITEM_BASE || itemId >= MM_MASK_ITEM_BASE + 24)
        return nullptr;

    int idx = itemId - MM_MASK_ITEM_BASE;
    if (sMaskNameLoaded[idx])
        return sCachedMaskNames[idx];

    sMaskNameLoaded[idx] = true;
    sCachedMaskNames[idx] = MmAssets_LoadResource(sMmMaskNamePaths[idx]);
    if (sCachedMaskNames[idx]) {
        MMASSETS_LOG("[MM Masks] Loaded name %d: %s", idx, sMmMaskNamePaths[idx]);
    }
    return sCachedMaskNames[idx];
}

// =============================================================================
// FD Sword Icon (for B-button HUD override)
// =============================================================================

static void* sCachedFDSwordIcon = nullptr;
static bool sFDSwordIconLoaded = false;

void* MmAssets_LoadFDSwordIcon(void) {
    if (!MmAssets_IsAvailable())
        return nullptr;
    if (sFDSwordIconLoaded)
        return sCachedFDSwordIcon;

    sFDSwordIconLoaded = true;
    sCachedFDSwordIcon = MmAssets_LoadResource("__OTR__icon_item_static_yar/gItemIconFierceDeitySwordTex");
    if (sCachedFDSwordIcon) {
        MMASSETS_LOG("[MM Assets] Loaded FD sword icon");
    }
    return sCachedFDSwordIcon;
}

} // extern "C"

// =============================================================================
// MM Asset Path Constants
// These are the paths used by 2Ship Keiichi Alfa 4.0.0
// =============================================================================

namespace MmAssetPaths {
// Goron Link assets
const char* GORON_SKELETON = "objects/object_link_goron/gLinkGoronSkel";
const char* GORON_HEAD_DL = "objects/object_link_goron/gLinkGoronHeadDL";
const char* GORON_CURLED_DL = "objects/object_link_goron/gLinkGoronCurledDL";
const char* GORON_SPIKES_DL = "objects/object_link_goron/gLinkGoronRollingSpikesAndEffectDL";

// Zora Link assets
const char* ZORA_SKELETON = "objects/object_link_zora/gLinkZoraSkel";
const char* ZORA_HEAD_DL = "objects/object_link_zora/gLinkZoraHeadDL";

// Deku Link assets
const char* DEKU_SKELETON = "objects/object_link_nuts/gLinkDekuSkel";
const char* DEKU_HEAD_DL = "objects/object_link_nuts/gLinkDekuHeadDL";

// Fierce Deity assets
const char* FIERCE_DEITY_SKELETON = "objects/object_link_boy/gLinkFierceDeitySkel";

// Audio
const char* TRANSFORM_SFX = "audio/sfx/NA_SE_SY_TRANSFORM_MASK_FLASH";
} // namespace MmAssetPaths
