/**
 * mm_asset_loader.cpp - MM Asset Detection and Loading
 *
 * Detects and loads assets from mm.o2r (generated by 2Ship2Harkinian Keiichi Alfa 4.0.0+)
 * This allows Transformation Masks to use actual MM models, audio, and animations.
 *
 * DEPENDENCY: 2Ship2Harkinian Keiichi Alfa 4.0.0 or later
 * https://github.com/HarbourMasters/2ship2harkinian/releases/tag/4.0.0
 *
 * Users must:
 * 1. Own a legal copy of Majora's Mask (US 1.0 or US GC)
 * 2. Run 2Ship2Harkinian to extract mm.o2r from their ROM
 * 3. Place mm.o2r in the same folder as soh.exe (alongside oot.o2r)
 *
 * NO RECOMPILATION NEEDED - just drop mm.o2r and enable the feature.
 */

#include "mm_asset_loader.h"
#include <filesystem>
#include <cstring>
#include <libultraship/libultraship.h>
#include <libultraship/log/luslog.h>
#include "soh/OTRGlobals.h"
#include "soh/ResourceManagerHelpers.h"
#include "functions.h" // For Audio_SetFontInstrument, AudioLoad_IsFontLoadComplete

// Logging macros (same pattern as mm_anim_loader.c)
#define MMASSETS_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)
#define MMSFX_LOG(fmt, ...) lusprintf(__FILE__, __LINE__, LUSLOG_LEVEL_INFO, fmt, ##__VA_ARGS__)

// Static state - base MM archive
static bool sMmO2rDetected = false;
static bool sMmO2rLoaded = false;
static bool sInitialized = false;
static std::string sMmO2rPath;
static std::shared_ptr<Ship::Archive> sMmArchive; // Reference to mm.o2r archive for archive-specific loading

// Mod override archive (higher priority than mm.o2r)
static bool sModO2rDetected = false;
static bool sModO2rLoaded = false;
static std::string sModO2rPath;

// Mod archive names to search for (in priority order)
static const char* sModArchiveNames[] = {
    "mm-mod.o2r",      // Primary mod file
    "mm-custom.o2r",   // Alternative name
    "mm-override.o2r", // Alternative name
};
static const int sModArchiveCount = sizeof(sModArchiveNames) / sizeof(sModArchiveNames[0]);

// appShortName is defined in OTRGlobals.h as const std::string

/**
 * Check if mm.o2r exists in any of the app directories
 * Uses the same search paths as oot.o2r
 */
static bool DetectMmO2r() {
    // Search for mm.o2r using the same method as oot.o2r
    std::string mmPath = Ship::Context::LocateFileAcrossAppDirs("mm.o2r", appShortName);
    if (!mmPath.empty() && std::filesystem::exists(mmPath)) {
        sMmO2rPath = mmPath;
        MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", mmPath.c_str());
        return true;
    }

    // Also check current working directory
    if (std::filesystem::exists("mm.o2r")) {
        sMmO2rPath = "mm.o2r";
        MMASSETS_LOG("[MM Assets] Found mm.o2r in current directory");
        return true;
    }

    // Check build output directories (for development)
    const char* buildPaths[] = {
        "x64/Debug/mm.o2r",
        "x64/Release/mm.o2r",
        "build/x64/mm.o2r",
        "../mm.o2r",
    };
    for (const char* path : buildPaths) {
        if (std::filesystem::exists(path)) {
            sMmO2rPath = path;
            MMASSETS_LOG("[MM Assets] Found mm.o2r at: %s", path);
            return true;
        }
    }

    MMASSETS_LOG("[MM Assets] mm.o2r NOT FOUND");
    return false;
}

/**
 * Check if a mod .o2r exists that can override mm.o2r assets
 * Searches for mm-mod.o2r, mm-custom.o2r, etc.
 */
static bool DetectModO2r() {
    for (int i = 0; i < sModArchiveCount; i++) {
        const char* modName = sModArchiveNames[i];

        // Search using standard path resolver
        std::string modPath = Ship::Context::LocateFileAcrossAppDirs(modName, appShortName);
        if (!modPath.empty() && std::filesystem::exists(modPath)) {
            sModO2rPath = modPath;
            MMASSETS_LOG("[MM Assets] Found mod override: %s", modPath.c_str());
            return true;
        }

        // Check current directory
        if (std::filesystem::exists(modName)) {
            sModO2rPath = modName;
            MMASSETS_LOG("[MM Assets] Found mod override in current directory: %s", modName);
            return true;
        }
    }

    return false;
}

/**
 * Load mod .o2r into the archive manager (before mm.o2r for priority)
 */
static bool LoadModO2r() {
    if (sModO2rLoaded || sModO2rPath.empty()) {
        return sModO2rLoaded;
    }

    if (!std::filesystem::exists(sModO2rPath)) {
        return false;
    }

    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sModO2rPath);
        if (archive != nullptr) {
            sModO2rLoaded = true;
            MMASSETS_LOG("[MM Assets] Loaded mod override archive: %s", sModO2rPath.c_str());
            return true;
        }
    }

    return false;
}

/**
 * Load mm.o2r into the archive manager
 * Same pattern as oot-mq.o2r loading in OTRGlobals::Initialize()
 */
static bool LoadMmO2r() {
    if (sMmO2rLoaded) {
        return true;
    }

    if (sMmO2rPath.empty() || !std::filesystem::exists(sMmO2rPath)) {
        MMASSETS_LOG("[MM Assets] Cannot load - path empty or file doesn't exist");
        return false;
    }

    // Add mm.o2r to the archive manager - same as oot.o2r/oot-mq.o2r
    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (archiveManager) {
        auto archive = archiveManager->AddArchive(sMmO2rPath);
        if (archive != nullptr) {
            sMmO2rLoaded = true;
            sMmArchive = archive; // Store for archive-specific loading
            MMASSETS_LOG("[MM Assets] Successfully loaded mm.o2r as archive (ptr=%p)", (void*)archive.get());
            return true;
        } else {
            MMASSETS_LOG("[MM Assets] Failed to add mm.o2r as archive");
            return false;
        }
    }

    MMASSETS_LOG("[MM Assets] No archive manager available");
    return false;
}

// =============================================================================
// C API Implementation
// =============================================================================

extern "C" {

void MmAssets_Init(void) {
    if (sInitialized) {
        return;
    }

    // Detect base MM archive
    sMmO2rDetected = DetectMmO2r();

    // Detect mod override archive
    sModO2rDetected = DetectModO2r();

    sInitialized = true;

    // Load base MM archive FIRST (lower priority)
    if (sMmO2rDetected) {
        LoadMmO2r();
    }

    // Load mod archive LAST (higher priority - overrides mm.o2r)
    // Ship's ResourceManager uses last-added-wins for duplicate resources
    if (sModO2rDetected) {
        LoadModO2r();
    }

    // Summary
    if (sModO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Mod override active - %s overrides mm.o2r", sModO2rPath.c_str());
    }
}

u8 MmAssets_IsAvailable(void) {
    if (!sInitialized) {
        MmAssets_Init();
    }
    return sMmO2rDetected ? 1 : 0;
}

u8 MmAssets_IsLoaded(void) {
    return sMmO2rLoaded ? 1 : 0;
}

u8 MmAssets_IsModLoaded(void) {
    return sModO2rLoaded ? 1 : 0;
}

const char* MmAssets_GetModPath(void) {
    return sModO2rPath.c_str();
}

const char* MmAssets_GetRequiredVersion(void) {
    return "2Ship2Harkinian Keiichi Alfa 4.0.0";
}

const char* MmAssets_GetDownloadUrl(void) {
    return "https://github.com/HarbourMasters/2ship2harkinian/releases/tag/4.0.0";
}

const char* MmAssets_GetPath(void) {
    return sMmO2rPath.c_str();
}

/**
 * Load a resource from mm.o2r
 * Path format follows 2Ship convention: "objects/object_link_goron/gLinkGoronSkel"
 *
 * @param path Resource path within mm.o2r
 * @return Pointer to loaded resource, or NULL if not found/not loaded
 */
void* MmAssets_LoadResource(const char* path) {
    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] No resource manager");
        return nullptr;
    }

    // Load resource from mm.o2r using standard resource loading
    auto resource = resourceManager->LoadResource(path);
    if (resource) {
        void* ptr = resource->GetRawPointer();
        MMASSETS_LOG("[MM Assets] Loaded: %s -> %p", path, ptr);
        return ptr;
    }

    MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    return nullptr;
}

/**
 * Load a resource from mm.o2r and get its size
 * @param path Resource path
 * @param outSize Output: size in bytes
 * @return Pointer to loaded resource, or NULL if not found
 */
void* MmAssets_LoadResourceWithSize(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmO2rLoaded) {
        MMASSETS_LOG("[MM Assets] Cannot load resource - mm.o2r not loaded");
        return nullptr;
    }
    if (path == nullptr) {
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] No resource manager");
        return nullptr;
    }

    auto resource = resourceManager->LoadResource(path);
    if (resource) {
        void* ptr = resource->GetRawPointer();
        size_t size = resource->GetPointerSize();
        if (outSize)
            *outSize = size;
        MMASSETS_LOG("[MM Assets] Loaded with size: %s -> %p (%zu bytes)", path, ptr, size);
        return ptr;
    }

    MMASSETS_LOG("[MM Assets] Failed to load: %s", path);
    return nullptr;
}

/**
 * Load a resource SPECIFICALLY from mm.o2r archive, bypassing the resource cache.
 *
 * CRITICAL: The normal LoadResource() path hits the ResourceManager cache, which may
 * contain OOT versions of resources with the same path (e.g., "audio/fonts/Soundfont_0"
 * exists in both oot.o2r and mm.o2r). By using ResourceIdentifier with the mm.o2r
 * archive as Parent, we get a separate cache entry that loads from mm.o2r specifically.
 *
 * @param path Resource path (e.g., "audio/fonts/Soundfont_0")
 * @param outSize Output: size in bytes (optional, can be NULL)
 * @return Pointer to loaded resource data, or NULL if not found
 */
static void* MmAssets_LoadFromMmArchive(const char* path, size_t* outSize) {
    if (outSize)
        *outSize = 0;

    if (!sMmArchive || !path) {
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: archive=%p, path=%s", (void*)sMmArchive.get(),
                     path ? path : "NULL");
        return nullptr;
    }

    auto resourceManager = OTRGlobals::Instance->context->GetResourceManager();
    if (!resourceManager) {
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: no resource manager");
        return nullptr;
    }

    // Use ResourceIdentifier with explicit Parent archive.
    // This creates a SEPARATE cache key from the default (OOT) version,
    // because the cache hash includes the Parent archive path.
    Ship::ResourceIdentifier identifier(path, 0, sMmArchive);
    auto resource = resourceManager->LoadResource(identifier);
    if (resource) {
        void* ptr = resource->GetRawPointer();
        size_t size = resource->GetPointerSize();
        if (outSize)
            *outSize = size;
        MMASSETS_LOG("[MM Assets] LoadFromMmArchive OK: %s -> %p (%zu bytes)", path, ptr, size);
        return ptr;
    }

    MMASSETS_LOG("[MM Assets] LoadFromMmArchive FAIL: %s not found in mm.o2r", path);
    return nullptr;
}

/**
 * Check if a specific resource exists in mm.o2r
 * Attempts to load the resource and checks if it succeeded
 */
u8 MmAssets_ResourceExists(const char* path) {
    if (!sMmO2rLoaded || path == nullptr) {
        return 0;
    }

    // Try to load and check if it succeeded
    void* resource = MmAssets_LoadResource(path);
    return (resource != nullptr) ? 1 : 0;
}

/**
 * List files matching a pattern from mm.o2r
 * Same as ResourceMgr_ListFiles in 2Ship (load.c lines 1254-1258)
 *
 * @param searchMask Pattern to match (e.g., "audio/fonts*")
 * @param resultSize Output: number of matching files
 * @return Array of file paths (caller must free), or NULL if none found
 */
char** MmAssets_ListFiles(const char* searchMask, int* resultSize) {
    if (!sMmO2rLoaded || searchMask == nullptr || resultSize == nullptr) {
        if (resultSize)
            *resultSize = 0;
        return nullptr;
    }

    auto archiveManager = OTRGlobals::Instance->context->GetResourceManager()->GetArchiveManager();
    if (!archiveManager) {
        *resultSize = 0;
        return nullptr;
    }

    // List files matching pattern from the archive
    // Same pattern as 2Ship's ResourceMgr_ListFiles (BenPort.cpp lines 315-332)
    auto fileList = archiveManager->ListFiles(searchMask);
    if (!fileList || fileList->size() == 0) {
        *resultSize = 0;
        MMASSETS_LOG("[MM Assets] No files match pattern: %s", searchMask);
        return nullptr;
    }

    // Convert to C-style array
    size_t count = fileList->size();
    char** result = (char**)malloc(count * sizeof(char*));
    if (!result) {
        *resultSize = 0;
        return nullptr;
    }

    for (size_t i = 0; i < count; i++) {
        const std::string& path = (*fileList)[i];
        result[i] = (char*)malloc(path.size() + 1);
        if (result[i]) {
            memcpy(result[i], path.c_str(), path.size());
            result[i][path.size()] = '\0';
        }
    }

    *resultSize = (int)count;
    MMASSETS_LOG("[MM Assets] Found %d files matching: %s", (int)count, searchMask);
    return result;
}

// =============================================================================
// Asset Replacement System
// =============================================================================

// MM asset paths for replacements (from mm_sources/archives/)
// Icons (32x32 RGBA from icon_item_static_yar)
#define MM_DEKU_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconDekuMaskTex"
#define MM_STONE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconStoneMaskTex"
#define MM_FIERCE_MASK_ICON_PATH "__OTR__icon_item_static_yar/gItemIconFierceDeityMaskTex"

// Name textures (from item_name_static)
#define MM_DEKU_MASK_NAME_PATH "__OTR__item_name_static/gItemNameDekuMaskENGTex"
#define MM_STONE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameStoneMaskENGTex"
#define MM_FIERCE_MASK_NAME_PATH "__OTR__item_name_static/gItemNameFierceDeitysMaskENGTex"

// Get Item DLs (3D models from object_gi_*)
// Each mask has TWO DLs drawn with specific render modes (from 2Ship z_draw.c):
// - Deku: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Stone: GetItem_DrawOpa0Xlu1 -> EmptyDL (Opa) + MaskDL (Xlu)
// - Fierce: GetItem_DrawOpa01 -> FaceDL (Opa) + HairDL (Opa)

// Deku Mask - object_gi_nutsmask
#define MM_DEKU_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskEmptyDL"
#define MM_DEKU_MASK_DL_PATH "__OTR__objects/object_gi_nutsmask/gGiDekuMaskDL"

// Stone Mask - object_gi_stonemask
#define MM_STONE_MASK_EMPTY_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskEmptyDL"
#define MM_STONE_MASK_DL_PATH "__OTR__objects/object_gi_stonemask/gGiStoneMaskDL"

// Fierce Deity - object_gi_mask03 (NOT object_gi_mask18 which is Captain's Hat)
#define MM_FIERCE_MASK_FACE_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskFaceDL"
#define MM_FIERCE_MASK_HAIR_DL_PATH "__OTR__objects/object_gi_mask03/gGiFierceDeityMaskHairAndHatDL"

// =============================================================================
// Worn Mask DLs (when Link wears mask on face - DIFFERENT from Get Item DLs!)
// =============================================================================
// These are drawn on Link's face when equipping a mask.
// Transformation masks (Deku, Goron, Zora, Fierce) use gameplay_keep DLs.
// Stone Mask uses its own object file (object_mask_stone).
// From 2Ship z_player_lib.c lines 2918-2926:
//   object_mask_stone_DL_000820,    // PLAYER_MASK_STONE
//   gFierceDeityMaskDL,             // PLAYER_MASK_FIERCE_DEITY (gameplay_keep)
//   gDekuMaskDL,                    // PLAYER_MASK_DEKU (gameplay_keep)

#define MM_DEKU_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gDekuMaskDL"
#define MM_STONE_MASK_WORN_DL_PATH "__OTR__objects/object_mask_stone/object_mask_stone_DL_000820"
#define MM_FIERCE_MASK_WORN_DL_PATH "__OTR__objects/gameplay_keep/gFierceDeityMaskDL"

// Replacement table entry
typedef struct {
    const char* ootPath;  // OOT path (without __OTR__ prefix)
    const char* mmPath;   // MM path (with __OTR__ prefix)
    const char* cvarName; // CVar that controls this replacement
    MmReplaceType type;   // Asset type
} MmAssetReplacementEntry;

// Static replacement table - all transformation mask replacements
static MmAssetReplacementEntry sReplacementTable[] = {
    // =========================================================================
    // Skull Mask → Deku Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSkullTex", MM_DEKU_MASK_ICON_PATH,
      "gMods.TransformMasks.DekuReplacesSkull", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSkullNameTex", MM_DEKU_MASK_NAME_PATH, "gMods.TransformMasks.DekuReplacesSkull",
      MM_REPLACE_TEXT },
    // =========================================================================
    // Spooky Mask → Stone Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskSpookyTex", MM_STONE_MASK_ICON_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskSpookyNameTex", MM_STONE_MASK_NAME_PATH,
      "gMods.TransformMasks.StoneReplacesSpooky", MM_REPLACE_TEXT },
    // =========================================================================
    // Gerudo Mask → Fierce Deity Mask (Icon, Name, Model)
    // =========================================================================
    { "textures/icon_item_static/gItemIconMaskGerudoTex", MM_FIERCE_MASK_ICON_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_ICON },
    { "textures/nes_font_static/gMaskGerudoNameTex", MM_FIERCE_MASK_NAME_PATH,
      "gMods.TransformMasks.FierceReplacesGerudo", MM_REPLACE_TEXT },
};
static const int sReplacementTableSize = sizeof(sReplacementTable) / sizeof(sReplacementTable[0]);

u8 MmAssets_IsReplacementActive(const char* cvarName) {
    if (!MmAssets_IsAvailable()) {
        return 0;
    }
    if (cvarName == nullptr) {
        return 0;
    }
    // Check CVar value
    return CVarGetInteger(cvarName, 0) ? 1 : 0;
}

const char* MmAssets_GetReplacement(const char* ootPath) {
    if (ootPath == nullptr || !MmAssets_IsAvailable()) {
        return nullptr;
    }

    // Strip __OTR__ prefix if present for comparison
    const char* pathToMatch = ootPath;
    if (strncmp(ootPath, "__OTR__", 7) == 0) {
        pathToMatch = ootPath + 7;
    }

    // Search replacement table
    for (int i = 0; i < sReplacementTableSize; i++) {
        const MmAssetReplacementEntry* entry = &sReplacementTable[i];
        if (strcmp(pathToMatch, entry->ootPath) == 0) {
            // Check if this replacement is active
            if (MmAssets_IsReplacementActive(entry->cvarName)) {
                MMASSETS_LOG("[MM Assets] Replacing %s -> %s", ootPath, entry->mmPath);
                return entry->mmPath;
            }
        }
    }

    return nullptr; // No replacement
}

void* MmAssets_LoadDekuMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskIcon: mm.o2r not available");
        return nullptr;
    }

    void* icon = MmAssets_LoadResource(MM_DEKU_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask icon from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask icon");
    }
    return icon;
}

void* MmAssets_LoadDekuMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        MMASSETS_LOG("[MM Assets] LoadDekuMaskNameText: mm.o2r not available");
        return nullptr;
    }

    void* nameText = MmAssets_LoadResource(MM_DEKU_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Deku Mask name text from mm.o2r");
    } else {
        MMASSETS_LOG("[MM Assets] Failed to load Deku Mask name text");
    }
    return nameText;
}

// =============================================================================
// Stone Mask Loaders (replaces Spooky Mask)
// =============================================================================

void* MmAssets_LoadStoneMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* icon = MmAssets_LoadResource(MM_STONE_MASK_ICON_PATH);
    if (icon != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask icon from mm.o2r");
    }
    return icon;
}

void* MmAssets_LoadStoneMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    void* nameText = MmAssets_LoadResource(MM_STONE_MASK_NAME_PATH);
    if (nameText != nullptr) {
        MMASSETS_LOG("[MM Assets] Loaded Stone Mask name text from mm.o2r");
    }
    return nameText;
}

void* MmAssets_LoadStoneMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_STONE_MASK_DL_PATH;
}

// =============================================================================
// Fierce Deity Mask Loaders
// =============================================================================

void* MmAssets_LoadFierceMaskIcon(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_ICON_PATH);
}

void* MmAssets_LoadFierceMaskNameText(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return MmAssets_LoadResource(MM_FIERCE_MASK_NAME_PATH);
}

void* MmAssets_LoadFierceMaskFaceDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_FACE_DL_PATH;
}

void* MmAssets_LoadFierceMaskHairDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    // Return path string - Ship resolves DL paths automatically in gSPDisplayList
    return (void*)MM_FIERCE_MASK_HAIR_DL_PATH;
}

// =============================================================================
// Deku Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadDekuMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_EMPTY_DL_PATH;
}

void* MmAssets_LoadDekuMaskDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_DEKU_MASK_DL_PATH;
}

// =============================================================================
// Stone Mask DL Loaders (TWO DLs: Empty + Mask, drawn as Opa0Xlu1)
// =============================================================================

void* MmAssets_LoadStoneMaskEmptyDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    return (void*)MM_STONE_MASK_EMPTY_DL_PATH;
}

// =============================================================================
// Worn Mask DL Loaders (for Link wearing mask on face)
// =============================================================================
// These DLs are DIFFERENT from Get Item DLs!
// Get Item: object_gi_* files (spinning 3D model when receiving)
// Worn: gameplay_keep or object_mask_* (attached to Link's face)

void* MmAssets_LoadDekuMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Deku Mask WORN DL: %s", MM_DEKU_MASK_WORN_DL_PATH);
    return (void*)MM_DEKU_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadStoneMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Stone Mask WORN DL: %s", MM_STONE_MASK_WORN_DL_PATH);
    return (void*)MM_STONE_MASK_WORN_DL_PATH;
}

void* MmAssets_LoadFierceMaskWornDL(void) {
    if (!MmAssets_IsAvailable()) {
        return nullptr;
    }
    MMASSETS_LOG("[MM Assets] Loading Fierce Deity Mask WORN DL: %s", MM_FIERCE_MASK_WORN_DL_PATH);
    return (void*)MM_FIERCE_MASK_WORN_DL_PATH;
}

// =============================================================================
// MM SFX System - Direct Audio Bypass
// =============================================================================
// Decodes MM ADPCM samples to PCM and mixes directly into OOT's audio output.
// This bypasses OOT's entire SFX pipeline (which caches sound data at startup
// and cannot play injected samples during gameplay).
//
// Architecture:
//   Game thread: MmSfx_PlayAtPos() → decode ADPCM → add to playing list
//   Audio thread: MmDirectAudio_MixInto() → mix PCM into output buffer
// =============================================================================

// MM SFX ID macros (matching OOT's z64audio.h SFX_INDEX)
#define MM_SFX_BANK_SHIFT 12
#define MM_SFX_INDEX_MASK 0x03FF
#define MM_SFX_BANK_INDEX(sfxId) (((sfxId) >> MM_SFX_BANK_SHIFT) & 0xF)
#define MM_SFX_SOUND_INDEX(sfxId) ((sfxId)&MM_SFX_INDEX_MASK)

// MM Goron SFX IDs
#define MM_NA_SE_PL_GORON_ROLL 0x0990
#define MM_NA_SE_PL_GORON_BALL_CHARGE 0x08EB
#define MM_NA_SE_SY_TRANSFORM_MASK_FLASH 0x4835

#define MM_SFX_MAX_FONTS 16
#define MM_SFX_FONT_PATH_FMT "audio/fonts/Soundfont_%d"

// MM SFX sequence (NA_BGM_GENERAL_SFX) uses soundfont 0 as the main SFX font for all banks.
// Soundfont 0 contains both soundEffects[] (for banks 0-5) and drums[] (for voice bank 6).
static const s32 sMmBankToFontMap[] = { 0, 0, 0, 0, 0, 0, 0 };

// --- Font cache ---
typedef struct {
    s32 fontId;
    SoundFont* font;
    size_t sizeBytes;
} MmSfxCacheEntry;

static MmSfxCacheEntry sSfxCache[MM_SFX_MAX_FONTS];
static s32 sSfxCacheCount = 0;
static s32 sSfxInitialized = 0;
static f32 sTempFreqScale = 1.0f;

static void MmSfxCache_Init(void) {
    if (sSfxInitialized)
        return;
    for (s32 i = 0; i < MM_SFX_MAX_FONTS; i++) {
        sSfxCache[i].fontId = -1;
        sSfxCache[i].font = nullptr;
        sSfxCache[i].sizeBytes = 0;
    }
    sSfxCacheCount = 0;
    sSfxInitialized = 1;
}

static MmSfxCacheEntry* MmSfxCache_Find(s32 fontId) {
    for (s32 i = 0; i < sSfxCacheCount; i++) {
        if (sSfxCache[i].fontId == fontId)
            return &sSfxCache[i];
    }
    return nullptr;
}

static MmSfxCacheEntry* MmSfxCache_GetFree(void) {
    if (sSfxCacheCount < MM_SFX_MAX_FONTS)
        return &sSfxCache[sSfxCacheCount++];
    for (s32 i = 0; i < MM_SFX_MAX_FONTS - 1; i++)
        sSfxCache[i] = sSfxCache[i + 1];
    sSfxCacheCount = MM_SFX_MAX_FONTS - 1;
    return &sSfxCache[sSfxCacheCount++];
}

s32 MmSfx_IsAvailable(void) {
    return MmAssets_IsAvailable();
}

void MmSfx_Init(void) {
    MmSfxCache_Init();
}

void MmSfx_Shutdown(void) {
    MmDirectAudio_StopAll();
    MmSfx_FlushCache();
    sSfxInitialized = 0;
}

SoundFont* MmSfx_LoadFont(s32 fontId) {
    if (!sSfxInitialized)
        MmSfxCache_Init();
    if (fontId < 0 || fontId >= 7)
        return nullptr;
    if (!MmAssets_IsAvailable())
        return nullptr;

    MmSfxCacheEntry* cached = MmSfxCache_Find(fontId);
    if (cached && cached->font)
        return cached->font;

    char path[64];
    snprintf(path, sizeof(path), MM_SFX_FONT_PATH_FMT, fontId);

    size_t size = 0;
    void* resource = MmAssets_LoadFromMmArchive(path, &size);
    if (!resource) {
        MMSFX_LOG("[MmSfx] LoadFont FAIL: %s not found in mm.o2r", path);
        return nullptr;
    }

    SoundFont* font = static_cast<SoundFont*>(resource);
    MMSFX_LOG("[MmSfx] LoadFont(%d) OK: %u sfx, %u drums", fontId, font->numSfx, font->numDrums);

    MmSfxCacheEntry* entry = MmSfxCache_GetFree();
    if (entry) {
        entry->fontId = fontId;
        entry->font = font;
        entry->sizeBytes = size;
    }
    return font;
}

SoundFont* MmSfx_GetFontForSfx(u16 sfxId) {
    s32 bank = MM_SFX_BANK_INDEX(sfxId);
    if (bank < 0 || bank >= 7)
        return nullptr;
    return MmSfx_LoadFont(sMmBankToFontMap[bank]);
}

// =============================================================================
// Direct Audio: ADPCM Decoder
// =============================================================================
// Decodes N64 VADPCM (codec 0) and SMALL_ADPCM (codec 3) to s16 PCM.
// Algorithm: Block-based prediction using codebook (order=2, 8-sample sub-frames).

#define VADPCM_FRAME_ADPCM 9       // codec 0: 1 header + 8 data bytes
#define VADPCM_FRAME_SMALL_ADPCM 5 // codec 3: 1 header + 4 data bytes
#define VADPCM_SAMPLES_PER_FRAME 16

// Decode one ADPCM frame (16 samples)
// Algorithm matches soh/soh/mixer.c aADPCMdecImpl() exactly
static void MmDirectAudio_DecodeFrame(const u8* frame, s32 frameSize, s16* out, const s16* book, s32 order, s16* hist) {
    s32 shift = frame[0] >> 4;
    s32 pred = frame[0] & 0xF;
    const s16* tbl0 = &book[pred * order * 8];     // coefs for prev2
    const s16* tbl1 = &book[pred * order * 8 + 8]; // coefs for prev1
    const u8* data = &frame[1];

    // Extract and scale input nibbles per sub-frame (matching mixer.c)
    for (s32 half = 0; half < 2; half++) {
        s16 ins[8];
        s16 prev1 = hist[1]; // most recent
        s16 prev2 = hist[0]; // second most recent

        if (frameSize == VADPCM_FRAME_SMALL_ADPCM) {
            // codec 3: 2 bits per sample, 2 bytes per sub-frame
            const u8* p = &data[half * 2];
            for (s32 j = 0; j < 2; j++) {
                ins[j * 4] = (s16)(((s32)(p[j] >> 6) << 30) >> 30) << shift;
                ins[j * 4 + 1] = (s16)((((s32)(p[j] >> 4) & 0x3) << 30) >> 30) << shift;
                ins[j * 4 + 2] = (s16)((((s32)(p[j] >> 2) & 0x3) << 30) >> 30) << shift;
                ins[j * 4 + 3] = (s16)((((s32)(p[j]) & 0x3) << 30) >> 30) << shift;
            }
        } else {
            // codec 0: 4 bits per sample, 4 bytes per sub-frame
            const u8* p = &data[half * 4];
            for (s32 j = 0; j < 4; j++) {
                ins[j * 2] = (s16)(((s32)(p[j] >> 4) << 28) >> 28) << shift;
                ins[j * 2 + 1] = (s16)((((s32)(p[j]) & 0xF) << 28) >> 28) << shift;
            }
        }

        // Core prediction loop - RECURSIVE within sub-frame (matching mixer.c:220-227)
        for (s32 j = 0; j < 8; j++) {
            s32 acc = tbl0[j] * prev2 + tbl1[j] * prev1 + ((s32)ins[j] << 11);
            for (s32 k = 0; k < j; k++) {
                acc += tbl1[((j - k) - 1)] * ins[k];
            }
            acc >>= 11;
            if (acc > 32767)
                acc = 32767;
            if (acc < -32768)
                acc = -32768;
            out[half * 8 + j] = (s16)acc;
        }

        // Update history for next sub-frame
        hist[0] = out[half * 8 + 6]; // second most recent
        hist[1] = out[half * 8 + 7]; // most recent
    }
}

// Decode entire ADPCM sample to PCM buffer
static s16* MmDirectAudio_DecodeADPCM(SoundFontSample* sample, u32* outLength) {
    if (!sample || !sample->sampleAddr || sample->size == 0)
        return nullptr;

    s32 frameSize;
    switch (sample->codec) {
        case 0:
            frameSize = VADPCM_FRAME_ADPCM;
            break;
        case 3:
            frameSize = VADPCM_FRAME_SMALL_ADPCM;
            break;
        default:
            MMSFX_LOG("[MmDirectAudio] Unsupported codec %d", sample->codec);
            return nullptr;
    }

    if (!sample->book || !sample->book->book) {
        MMSFX_LOG("[MmDirectAudio] No codebook for sample");
        return nullptr;
    }

    u32 numFrames = sample->size / frameSize;
    u32 totalSamples = numFrames * VADPCM_SAMPLES_PER_FRAME;

    // Limit to loop end if looping
    if (sample->loop && sample->loop->loopEnd > 0 && sample->loop->loopEnd < totalSamples) {
        totalSamples = sample->loop->loopEnd;
        numFrames = (totalSamples + VADPCM_SAMPLES_PER_FRAME - 1) / VADPCM_SAMPLES_PER_FRAME;
    }

    s16* pcm = (s16*)malloc(totalSamples * sizeof(s16));
    if (!pcm)
        return nullptr;

    s16 hist[2] = { 0, 0 };
    const u8* src = (const u8*)sample->sampleAddr;
    s32 order = sample->book->order;
    const s16* book = sample->book->book;

    for (u32 f = 0; f < numFrames; f++) {
        s16 frameBuf[VADPCM_SAMPLES_PER_FRAME];
        MmDirectAudio_DecodeFrame(&src[f * frameSize], frameSize, frameBuf, book, order, hist);

        u32 dstOffset = f * VADPCM_SAMPLES_PER_FRAME;
        u32 count = VADPCM_SAMPLES_PER_FRAME;
        if (dstOffset + count > totalSamples) {
            count = totalSamples - dstOffset;
        }
        memcpy(&pcm[dstOffset], frameBuf, count * sizeof(s16));
    }

    *outLength = totalSamples;
    return pcm;
}

// =============================================================================
// Direct Audio: Playing Sound List + Mixer
// =============================================================================

#define MM_DIRECT_MAX_SOUNDS 8

typedef struct {
    s16* pcmData;    // Decoded PCM buffer (allocated, must be freed)
    u32 pcmLength;   // Total samples in buffer
    f32 pcmPosition; // Current fractional playback position
    f32 advance;     // Samples to advance per output sample (tuning * freqScale)
    f32 volume;      // Volume [0..1]
    f32 pan;         // Pan [0=left, 0.5=center, 1=right]
    u16 mmSfxId;     // MM SFX ID for stop/identify
    u8 active;       // 1=playing, 0=free
} MmPlayingSound;

static MmPlayingSound sPlayingSounds[MM_DIRECT_MAX_SOUNDS];

// Get SoundFontSound for an MM SFX ID (handles voice bank drum mapping)
static SoundFontSound* MmDirectAudio_GetSound(u16 mmSfxId) {
    SoundFont* font = MmSfx_GetFontForSfx(mmSfxId);
    if (!font)
        return nullptr;

    s32 bank = MM_SFX_BANK_INDEX(mmSfxId);
    s32 sfxIndex = MM_SFX_SOUND_INDEX(mmSfxId);

    // Voice bank (6) stores voices as drums in soundfont 0.
    // The drum index IS the SFX index directly (e.g., 0xC5 = drum 197 for Goron damage).
    if (bank == 6 && font->numDrums > 0) {
        MMSFX_LOG("[MmDirectAudio] Voice lookup: sfxId=0x%04X, sfxIndex=%d, numDrums=%u", mmSfxId, sfxIndex,
                  font->numDrums);

        if ((u32)sfxIndex >= font->numDrums || !font->drums || !font->drums[sfxIndex])
            return nullptr;
        return &font->drums[sfxIndex]->sound;
    }

    // Regular SFX bank - uses soundEffects[] array
    if ((u32)sfxIndex >= font->numSfx)
        return nullptr;
    return &font->soundEffects[sfxIndex];
}

// Start playing an MM sound
static void MmDirectAudio_Play(u16 mmSfxId, f32 freqScale) {
    SoundFontSound* sfxSound = MmDirectAudio_GetSound(mmSfxId);
    if (!sfxSound || !sfxSound->sample) {
        MMSFX_LOG("[MmDirectAudio] No sample for 0x%04X", mmSfxId);
        return;
    }

    u32 pcmLength = 0;
    s16* pcm = MmDirectAudio_DecodeADPCM(sfxSound->sample, &pcmLength);
    if (!pcm || pcmLength == 0) {
        MMSFX_LOG("[MmDirectAudio] Decode failed for 0x%04X", mmSfxId);
        return;
    }

    // Find free slot (or evict oldest)
    s32 freeSlot = -1;
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        if (!sPlayingSounds[i].active) {
            freeSlot = i;
            break;
        }
    }
    if (freeSlot < 0) {
        freeSlot = 0;
        if (sPlayingSounds[0].pcmData)
            free(sPlayingSounds[0].pcmData);
        sPlayingSounds[0].pcmData = nullptr;
        sPlayingSounds[0].active = 0;
    }

    MmPlayingSound* snd = &sPlayingSounds[freeSlot];
    if (snd->pcmData)
        free(snd->pcmData);

    snd->pcmData = pcm;
    snd->pcmLength = pcmLength;
    snd->pcmPosition = 0.0f;
    snd->advance = sfxSound->tuning * freqScale;
    snd->volume = 0.8f;
    snd->pan = 0.5f;
    snd->mmSfxId = mmSfxId;
    snd->active = 1;

    MMSFX_LOG("[MmDirectAudio] Playing 0x%04X: %u samples, tuning=%.3f, freq=%.3f, advance=%.3f, codec=%d, size=%u, "
              "order=%d, npred=%d",
              mmSfxId, pcmLength, sfxSound->tuning, freqScale, snd->advance, sfxSound->sample->codec,
              sfxSound->sample->size, sfxSound->sample->book ? sfxSound->sample->book->order : -1,
              sfxSound->sample->book ? sfxSound->sample->book->npredictors : -1);
}

// Mix all active MM sounds into the output buffer (called from audio thread)
// outBuf: interleaved stereo s16 [L0,R0,L1,R1,...], numSamples = stereo pairs
void MmDirectAudio_MixInto(s16* outBuf, u32 numSamples) {
    for (s32 slot = 0; slot < MM_DIRECT_MAX_SOUNDS; slot++) {
        MmPlayingSound* snd = &sPlayingSounds[slot];
        if (!snd->active || !snd->pcmData)
            continue;

        f32 volL = snd->volume * (1.0f - snd->pan);
        f32 volR = snd->volume * snd->pan;

        for (u32 i = 0; i < numSamples; i++) {
            u32 pos = (u32)snd->pcmPosition;
            if (pos >= snd->pcmLength - 1) {
                snd->active = 0;
                break;
            }

            // Linear interpolation between adjacent samples
            f32 frac = snd->pcmPosition - (f32)pos;
            f32 sample = snd->pcmData[pos] * (1.0f - frac) + snd->pcmData[pos + 1] * frac;

            s32 outL = outBuf[i * 2] + (s32)(sample * volL);
            s32 outR = outBuf[i * 2 + 1] + (s32)(sample * volR);

            if (outL > 32767)
                outL = 32767;
            if (outL < -32768)
                outL = -32768;
            if (outR > 32767)
                outR = 32767;
            if (outR < -32768)
                outR = -32768;

            outBuf[i * 2] = (s16)outL;
            outBuf[i * 2 + 1] = (s16)outR;

            snd->pcmPosition += snd->advance;
        }
    }
}

// Stop a specific MM sound
static void MmDirectAudio_StopById(u16 mmSfxId) {
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        if (sPlayingSounds[i].active && sPlayingSounds[i].mmSfxId == mmSfxId) {
            sPlayingSounds[i].active = 0;
        }
    }
}

// Stop all MM sounds and free PCM buffers
void MmDirectAudio_StopAll(void) {
    for (s32 i = 0; i < MM_DIRECT_MAX_SOUNDS; i++) {
        sPlayingSounds[i].active = 0;
        if (sPlayingSounds[i].pcmData) {
            free(sPlayingSounds[i].pcmData);
            sPlayingSounds[i].pcmData = nullptr;
        }
    }
}

// =============================================================================
// MmSfx Public API (unchanged interface, new direct audio backend)
// =============================================================================

void MmSfx_PlayAtPos(u16 sfxId, Vec3f* pos) {
    MmSfx_PlayEx(sfxId, pos, 4, nullptr, nullptr, nullptr);
}

void MmSfx_PlayEx(u16 sfxId, Vec3f* pos, u8 token, f32* freqScale, f32* vol, s8* reverbAdd) {
    if (!MmAssets_IsAvailable())
        return;
    f32 freq = freqScale ? *freqScale : 1.0f;
    MmDirectAudio_Play(sfxId, freq);
}

void MmSfx_Stop(u16 sfxId) {
    MmDirectAudio_StopById(sfxId);
}

void MmSfx_PlayGoronRoll(Vec3f* pos, f32 speed) {
    sTempFreqScale = 0.8f + (speed / 20.0f) * 0.4f;
    if (sTempFreqScale > 1.5f)
        sTempFreqScale = 1.5f;
    if (sTempFreqScale < 0.5f)
        sTempFreqScale = 0.5f;
    MmSfx_PlayEx(MM_NA_SE_PL_GORON_ROLL, pos, 4, &sTempFreqScale, nullptr, nullptr);
}

void MmSfx_PlayGoronCharge(Vec3f* pos, f32 chargeLevel) {
    sTempFreqScale = 0.7f + chargeLevel * 0.6f;
    MmSfx_PlayEx(MM_NA_SE_PL_GORON_BALL_CHARGE, pos, 4, &sTempFreqScale, nullptr, nullptr);
}

void MmSfx_PlayTransformFlash(void) {
    MmSfx_PlayAtPos(MM_NA_SE_SY_TRANSFORM_MASK_FLASH, nullptr);
}

void MmSfx_GetCacheStats(s32* outLoadedFonts, s32* outTotalBytes) {
    if (outLoadedFonts)
        *outLoadedFonts = sSfxCacheCount;
    if (outTotalBytes) {
        size_t total = 0;
        for (s32 i = 0; i < sSfxCacheCount; i++)
            total += sSfxCache[i].sizeBytes;
        *outTotalBytes = (s32)total;
    }
}

void MmSfx_FlushCache(void) {
    for (s32 i = 0; i < MM_SFX_MAX_FONTS; i++) {
        sSfxCache[i].fontId = -1;
        sSfxCache[i].font = nullptr;
        sSfxCache[i].sizeBytes = 0;
    }
    sSfxCacheCount = 0;
}

} // extern "C"

// =============================================================================
// MM Asset Path Constants
// These are the paths used by 2Ship Keiichi Alfa 4.0.0
// =============================================================================

namespace MmAssetPaths {
// Goron Link assets
const char* GORON_SKELETON = "objects/object_link_goron/gLinkGoronSkel";
const char* GORON_HEAD_DL = "objects/object_link_goron/gLinkGoronHeadDL";
const char* GORON_CURLED_DL = "objects/object_link_goron/gLinkGoronCurledDL";
const char* GORON_SPIKES_DL = "objects/object_link_goron/gLinkGoronRollingSpikesAndEffectDL";

// Zora Link assets
const char* ZORA_SKELETON = "objects/object_link_zora/gLinkZoraSkel";
const char* ZORA_HEAD_DL = "objects/object_link_zora/gLinkZoraHeadDL";

// Deku Link assets
const char* DEKU_SKELETON = "objects/object_link_nuts/gLinkDekuSkel";
const char* DEKU_HEAD_DL = "objects/object_link_nuts/gLinkDekuHeadDL";

// Fierce Deity assets
const char* FIERCE_DEITY_SKELETON = "objects/object_link_boy/gLinkFierceDeitySkel";

// Audio
const char* TRANSFORM_SFX = "audio/sfx/NA_SE_SY_TRANSFORM_MASK_FLASH";
} // namespace MmAssetPaths
