/**
 * garo_hybrid_render.cpp — render the hybrid Garo skeleton.
 *
 * The hybrid lives in garo_hybrid.o2r (generated by tools/build_garo_hybrid_o2r.py):
 *   19 limbs = MM Garo upper body (0..11) + OOT Link adult lower body (12..18).
 *   DLs and textures live in mm.o2r and oot.o2r respectively; the hybrid
 *   .o2r only stores SkeletonLimb resources pointing at those external paths.
 *
 * This module:
 *   * Loads the hybrid skeleton + gGaroIdleAnim from mm.o2r at setup time
 *   * Maintains an independent SkelAnime (own jointTable + morphTable)
 *   * Each frame, populates jointTable from one of two anim sources:
 *       - GARO_NATIVE   (default): SkelAnime advances with the selected
 *                                  Garo anim (cloak ondea, swords swing)
 *       - LINK_RETARGET           : copy values from player->skelAnime via
 *                                  the bone counterpart table (Link's
 *                                  vanilla anims like climb/walk drive
 *                                  the hybrid body)
 *   * Draws at player's world pos with scale ~0.85 (between adult and child).
 *
 * The existing GaroForm_DrawNullBody path still hides Link's mesh; this
 * hybrid render replaces what GaroSkin_Draw used to produce.
 */

#include "garo_hybrid_render.h"
#include "soh/ResourceManagerHelpers.h"

#include <libultraship/bridge.h>
#include <spdlog/spdlog.h>
#include <cstring>

extern "C" {
#include "z64.h"
#include "macros.h"
#include "functions.h"
#include "variables.h"
}

// We use Garo enemy's OFFICIAL skeleton from mm.o2r — same 19-bone topology
// (ROOT, TORSO, L/R arms+swords, 5 robe bones, HEAD, LowerBodyRoot, 6 leg
// bones) at uniform Garo-scale. The custom green-robe textures in
// garo_hybrid.o2r override mm.o2r's at the same paths, so the model loads
// with Link's tunic colors while keeping Garo's full body proportions.
#define HYBRID_SKEL_OTR   "__OTR__objects/object_jso/gGaroSkel"
#define DEFAULT_ANIM_OTR  "__OTR__objects/object_jso/gGaroIdleAnim"

// Garo enemy skeleton has 19 limbs. jointTable needs limbCount+1 = 20 entries
// ([0] = root translation Vec3s, [1..19] = limb rotations).
#define HYBRID_LIMB_COUNT 19

// Per-bone source split (always merged, no mode CVar):
//   Body bones (head, torso, arms, legs) → Link's anim values via retarget
//     so climb/swim/walk/run drive Garo's body exactly like Link's body.
//   Sword bones + cloak Top/Back/Front → Garo's anim values from our own
//     SkelAnime so they swing/ondea independently (default: gGaroIdleAnim).
//   Cloak Left/Right → Link's L_SHOULDER / R_SHOULDER rotations so the side
//     panels of the robe move with Link's arms (climbing, swinging items,
//     etc.). Done as an EXPLICIT override after the main retarget loop in
//     GaroHybrid_Update.
//
// Hybrid jointTable bone slots kept verbatim from Garo's anim:
//   [4] L_SWORD  [6] R_SWORD
//   [7] ROBE_TOP [8] ROBE_BACK [11] ROBE_FRONT
// (Note: [9] ROBE_LEFT and [10] ROBE_RIGHT are explicitly overwritten with
//  Link's shoulder rotations below, so they're not "Garo bones" anymore.)
static inline bool IsGaroBone(s32 hybrid_jt_idx) {
    return (hybrid_jt_idx == 4) || (hybrid_jt_idx == 6) ||
           (hybrid_jt_idx == 7) || (hybrid_jt_idx == 8) ||
           (hybrid_jt_idx == 11);
}

static SkelAnime sSkelAnime = {};
static Vec3s sJointTable[HYBRID_LIMB_COUNT + 1] = {};
static Vec3s sMorphTable[HYBRID_LIMB_COUNT + 1] = {};
static AnimationHeader* sCurrentAnim = nullptr;
static bool sInitialized = false;

// PLAYER_LIMB enum index → hybrid jointTable index. -1 means "no counterpart"
// (the hybrid bone, if any, holds its rest-pose rotation when Link is the
// source). Hybrid jointTable layout:
//   [0] root translation     [1] ROOT       [2] TORSO
//   [3] L_ARM   [4] L_SWORD  [5] R_ARM      [6] R_SWORD
//   [7..11] ROBE_*           [12] HEAD
//   [13] LOWER  [14] R_THIGH [15] R_SHIN    [16] R_FOOT
//   [17] L_THIGH [18] L_SHIN [19] L_FOOT
//
// PLAYER_LIMB enum (z64player.h): NONE=0, ROOT=1, WAIST=2, LOWER=3,
// R_THIGH=4, R_SHIN=5, R_FOOT=6, L_THIGH=7, L_SHIN=8, L_FOOT=9, UPPER=10,
// HEAD=11, HAT=12, COLLAR=13, L_SHOULDER=14, L_FOREARM=15, L_HAND=16,
// R_SHOULDER=17, R_FOREARM=18, R_HAND=19, SHEATH=20, TORSO=21.
// Garo's LowerBodyRoot gets Link's WAIST rotation (not Lower). Reason:
// Link's chain is Root → Waist → LowerControl → Thigh; Waist drives the
// hip orientation while Lower is a near-zero control bone. Garo has only
// LowerBodyRoot at the same level as a Waist+Lower combined. Mapping
// Waist (which carries the meaningful hip motion in walk/run/swim anims)
// keeps the leg subtree oriented correctly while THIGH/SHIN/FOOT below
// inherit a stable parent frame from Link's perspective.
static const s8 sLinkLimbToHybridJt[22] = {
    -1,  // 0  NONE
     1,  // 1  ROOT       -> hybrid jt[1]  ROOT
    13,  // 2  WAIST      -> hybrid jt[13] LowerBodyRoot (hip orientation)
    -1,  // 3  LOWER      (skipped — Link's Lower is a near-zero control bone)
    14,  // 4  R_THIGH    -> hybrid jt[14] R_THIGH
    15,  // 5  R_SHIN     -> hybrid jt[15] R_SHIN
    16,  // 6  R_FOOT     -> hybrid jt[16] R_FOOT
    17,  // 7  L_THIGH    -> hybrid jt[17] L_THIGH
    18,  // 8  L_SHIN     -> hybrid jt[18] L_SHIN
    19,  // 9  L_FOOT     -> hybrid jt[19] L_FOOT
     2,  // 10 UPPER      -> hybrid jt[2]  TORSO (Garo's TORSO acts as Link's UPPER)
    12,  // 11 HEAD       -> hybrid jt[12] HEAD
    -1,  // 12 HAT        (no counterpart)
    -1,  // 13 COLLAR     (no counterpart)
     3,  // 14 L_SHOULDER -> hybrid jt[3]  L_ARM
    -1,  // 15 L_FOREARM  (Garo collapses forearm into L_ARM bone)
     4,  // 16 L_HAND     -> hybrid jt[4]  L_SWORD (sword in left hand)
     5,  // 17 R_SHOULDER -> hybrid jt[5]  R_ARM
    -1,  // 18 R_FOREARM
     6,  // 19 R_HAND     -> hybrid jt[6]  R_SWORD
    -1,  // 20 SHEATH     (no counterpart)
    -1,  // 21 TORSO      (Garo's TORSO already covered by UPPER mapping)
};

// Garo enemy is natively drawn at scale 0.035 (z_en_jso.c). Link adult is
// drawn at 0.01. Our outer matrix uses Link's 0.01 (so the actor sits at
// Link's world height), then we apply Matrix_Scale(3.5) at ROOT entry so
// Garo's entire skeleton (bone offsets AND DL vertices) renders at its
// native Garo-enemy size: 0.01 × 3.5 = 0.035.
#define GARO_SUBTREE_SCALE 3.5f

// ROOT bone arrives as jointTable index 1 in OverrideLimbDraw
// (SkelAnime_DrawFlexOpa hardcodes 1 — z_skelanime.c:475).
#define HYBRID_JT_ROOT_ENTRY 1

// 1.2× perpendicular scale applied at thigh entry to make Garo's legs
// thicker (request: legs but not feet). The bone's local +X is the limb
// length axis, so we scale Y/Z (cross-section) by 1.2 and X by 1.0.
// Inherits to the shin (child of thigh). Undone at the foot entry so
// boots stay at their original size.
#define LEG_THICK 1.3f
#define LEG_THICK_INV (1.0f / 1.3f)
// Garo enemy jointTable indices (jt = limb_index + 1):
//   jt[4]  L_SWORD (limb 3), jt[6]  R_SWORD (limb 5)
//   jt[14] R_THIGH (limb 13), jt[16] R_FOOT (limb 15)
//   jt[17] L_THIGH (limb 16), jt[19] L_FOOT (limb 18)
#define HYBRID_JT_L_SWORD 4
#define HYBRID_JT_R_SWORD 6
#define HYBRID_JT_R_THIGH 14
#define HYBRID_JT_R_FOOT  16
#define HYBRID_JT_L_THIGH 17
#define HYBRID_JT_L_FOOT  19

// Forward declarations
static void GaroHybrid_LoadAnim(PlayState* play, const char* otrPath, bool loop);
static s32  GaroHybrid_OverrideLimbDraw(PlayState* play, s32 limbIndex,
                                        Gfx** dList, Vec3f* pos, Vec3s* rot,
                                        void* arg);

extern "C" s32 GaroHybrid_Setup(PlayState* play) {
    if (sInitialized) return 1;

    SkeletonHeader* skel = ResourceMgr_LoadSkeletonByName(HYBRID_SKEL_OTR, NULL);
    if (skel == nullptr) {
        SPDLOG_WARN("[GaroHybrid] failed to load skeleton '{}'", HYBRID_SKEL_OTR);
        return 0;
    }

    AnimationHeader* anim = (AnimationHeader*)ResourceMgr_LoadAnimByName(DEFAULT_ANIM_OTR);
    if (anim == nullptr) {
        SPDLOG_WARN("[GaroHybrid] failed to load default anim '{}'", DEFAULT_ANIM_OTR);
        return 0;
    }

    SkelAnime_Init(play, &sSkelAnime, skel, anim, sJointTable, sMorphTable, HYBRID_LIMB_COUNT);
    Animation_PlayLoop(&sSkelAnime, anim);
    sCurrentAnim = anim;
    sInitialized = true;
    SPDLOG_INFO("[GaroHybrid] setup OK — {} limbs, idle anim playing", HYBRID_LIMB_COUNT);
    return 1;
}

extern "C" void GaroHybrid_Teardown(void) {
    if (!sInitialized) return;
    std::memset(&sSkelAnime, 0, sizeof(sSkelAnime));
    sCurrentAnim = nullptr;
    sInitialized = false;
}

extern "C" void GaroHybrid_Update(PlayState* play, Player* player) {
    if (!sInitialized) {
        if (!GaroHybrid_Setup(play)) return;
    }

    // 1. Advance Garo's anim through OUR SkelAnime — this writes Garo-native
    //    rotations into sJointTable[0..19] for ALL bones. Cloak ondea +
    //    sword swings come from these.
    SkelAnime_Update(&sSkelAnime);

    // 2. Overwrite body bones with Link's current pose so Link's anim
    //    (climb, swim, walk, run, item-pose…) drives head/torso/arms/legs.
    //    Sword bones + Top/Back/Front robe (IsGaroBone) keep the Garo-anim
    //    values from step 1.
    // 3. Robe Left/Right are EXPLICITLY mapped to Link's shoulder rotations
    //    so the side panels follow Link's arm motion. This is not part of
    //    the main retarget loop because sLinkLimbToHybridJt[L_SHOULDER]
    //    already points to L_ARM (jt[3]); we want shoulder values to feed
    //    TWO bones (the body's L_ARM AND the cloak's ROBE_LEFT).
    if (player->skelAnime.jointTable != nullptr) {
        Vec3s* link = player->skelAnime.jointTable;
        sJointTable[0] = link[0];  // root translation from Link
        for (s32 pl = 1; pl < 22; pl++) {
            s8 hjt = sLinkLimbToHybridJt[pl];
            if (hjt < 0) continue;
            if (IsGaroBone(hjt)) continue;
            sJointTable[hjt] = link[pl];
        }
        // PLAYER_LIMB_L_SHOULDER=14 → ROBE_LEFT (jt[9])
        // PLAYER_LIMB_R_SHOULDER=17 → ROBE_RIGHT (jt[10])
        sJointTable[9]  = link[14];
        sJointTable[10] = link[17];
    }
}

extern "C" void GaroHybrid_Draw(PlayState* play, Player* player) {
    if (!sInitialized) return;

    OPEN_DISPS(play->state.gfxCtx);

    // Render-state setup — required for Garo DLs from mm.o2r and Link DLs from
    // oot.o2r to render correctly. Without these calls vertices fail to
    // transform and only a tiny cluster appears in world space.
    //   * Gfx_SetupDL_25Opa: combiner / render-mode / geometry-mode for opaque
    //     character meshes (mirrors EnJso_Draw line 1663 in mm_decomp).
    //   * Segment 0x0C → gCullBackDList: backface-cull DList referenced by
    //     G_DL_INDEX inside MM-format DLs. Skipping it leaves segment 0x0C
    //     pointing at random memory and the DL aborts.
    Gfx_SetupDL_25Opa(play->state.gfxCtx);
    gSPSegment(POLY_OPA_DISP++, 0x0C, (uintptr_t)gCullBackDList);

    // Position at player's world pos with yaw, scaled to match Link's height.
    Matrix_Translate(player->actor.world.pos.x,
                     player->actor.world.pos.y,
                     player->actor.world.pos.z, MTXMODE_NEW);
    Matrix_RotateY((player->actor.shape.rot.y * (M_PI / 0x8000)), MTXMODE_APPLY);

    f32 scale = CVarGetFloat("gGaroHybrid.Scale", 0.01f);  // adult Link default
    Matrix_Scale(scale, scale, scale, MTXMODE_APPLY);

    // Use Flex draw — official Garo skel is Flex-typed and its DLs reference
    // matrices via segment 0x0D set up by DrawFlexOpa. DrawOpa (Normal) skips
    // that step and the per-limb matrix indirection breaks.
    //
    // OverrideLimbDraw injects Matrix_Scale(3.5) at the TORSO entry so Garo's
    // entire upper-body subtree (TORSO + arms + swords + 5 robe bones + head)
    // renders ~3.5× bigger to match Link adult's coord scale. The Link
    // lower-body subtree (LOWER + thighs + shins + feet, sibling of TORSO)
    // inherits no scale and renders at Link's native size.
    SkelAnime_DrawFlexOpa(play, sSkelAnime.skeleton, sSkelAnime.jointTable,
                          HYBRID_LIMB_COUNT,
                          GaroHybrid_OverrideLimbDraw,
                          /*postLimbDraw*/ NULL,
                          /*arg*/ player);

    CLOSE_DISPS(play->state.gfxCtx);
}

// OverrideLimbDraw — at ROOT entry (limbIndex 1), do the engine's
// Translate+Rotate manually at BASE scale (so Link's root translation lands
// at his real world height — Link adult anims encode (-57, 3377, 0)-ish
// values calibrated for 0.01 outer scale), THEN apply Matrix_Scale(3.5) so
// every descendant in Garo's skeleton (TORSO subtree + LowerBodyRoot
// subtree, both children of ROOT) inherits the Garo-native size (0.035).
//
// Returning 1 skips the engine's default Translate+Rotate+DL emit. ROOT in
// Garo's skel has no DL so nothing visual is lost.
static s32 GaroHybrid_OverrideLimbDraw(PlayState* play, s32 limbIndex,
                                       Gfx** dList, Vec3f* pos, Vec3s* rot,
                                       void* arg) {
    (void)play; (void)dList; (void)arg;

    if (limbIndex == HYBRID_JT_ROOT_ENTRY) {
        Matrix_TranslateRotateZYX(pos, rot);
        Matrix_Scale(GARO_SUBTREE_SCALE, GARO_SUBTREE_SCALE, GARO_SUBTREE_SCALE,
                     MTXMODE_APPLY);
        return 1;
    }
    // Thicker legs (not feet): inflate cross-section at thigh entry, undo
    // at foot entry so boots stay normal-sized. Shin inherits from thigh.
    if (limbIndex == HYBRID_JT_R_THIGH || limbIndex == HYBRID_JT_L_THIGH) {
        Matrix_Scale(1.0f, LEG_THICK, LEG_THICK, MTXMODE_APPLY);
    } else if (limbIndex == HYBRID_JT_R_FOOT || limbIndex == HYBRID_JT_L_FOOT) {
        Matrix_Scale(1.0f, LEG_THICK_INV, LEG_THICK_INV, MTXMODE_APPLY);
    }
    // TODO: Garo Master-sword DL swap stays disabled — both .o2r-level overrides
    // and runtime dList swaps crashed in gfx_vtx_hash_handler_custom (master
    // sword DL vertex hashes don't resolve in this load context). Garo wields
    // his native blades for now.
    return 0;
}

extern "C" void GaroHybrid_SetAnim(PlayState* play, const char* otrPath) {
    if (!sInitialized) {
        if (!GaroHybrid_Setup(play)) return;
    }
    GaroHybrid_LoadAnim(play, otrPath ? otrPath : DEFAULT_ANIM_OTR, true);
}

static void GaroHybrid_LoadAnim(PlayState* play, const char* otrPath, bool loop) {
    AnimationHeader* anim = (AnimationHeader*)ResourceMgr_LoadAnimByName(otrPath);
    if (anim == nullptr) {
        SPDLOG_WARN("[GaroHybrid] failed to load anim '{}'", otrPath);
        return;
    }
    if (anim == sCurrentAnim) return;
    sCurrentAnim = anim;
    if (loop) {
        Animation_PlayLoop(&sSkelAnime, anim);
    } else {
        Animation_PlayOnce(&sSkelAnime, anim);
    }
}
